= The Internet Nomad

Selling my condo a couple of years ago was liberating. Now I can throw my stuff in the car and move where and when I want. Seriously, that’s how I ended up in San Diego a few months ago — spontaneous road trip to Wondercon and then a spontaneous apartment-hunting trip to downtown San Diego (and then Vegas, but it was too damn hot. Back to San Diego).

I’m taking the same approach to my web sites. Last week I redirected technicat.com to my Medium profile and fugugames.com to my tumblr domain. Sure, like my old condo, it’s nice to have web sites that are distinctly mine and I can customize the way I want, and hopping around from rental to rental or social site to social site means losing some stuff each time and having to start nearly from scratch each time.

But, like my old condo, the maintenance was a hassle — time-consuming, and I really wasn’t good at it (my web design skills are about as good as my interior design skills, and my web programming skills are about as good as my home repair skills). Plus, when you move around, you meet new people and explore new neighborhoods. And if I don’t like it, or if I just get bored with it, I’ll just move on.
