= The Last of the Computer Bookstores

During my recent trip to Portland, I was saddened to see *Powell’s Technical Books* is no more, now just a portion of the third floor of Powell’s main store. And there are five floors (that’s why they call it https://www.powells.com/[Powell’s City of Books]).

But I wasn’t surprised. Every other computer bookstore I used to frequent is gone, already. It’s as if I left a trail of dead bookstores in my wake.

Los Angeles: *OpAmp Books* — a technical bookstore in Hollywood, as you would expect filled with books useful for the entertainment industry. Got some good computer graphics books, there.

San Diego: *San Diego Technical Books* — I only went there once, while I was living in Orange County. Bought some O’Reilly books there in some O’Reilly promotion which they terminated so I think O’Reilly owes me something.

Orange County: *Irvine Sci-Tech Books* — serving the decent high-tech presence around Irvine (they have a Google!). They had some good t-shirts.

Boston: *Quantum Books* — my favorite bookstore around MIT is still the MIT Press bookstore, but it was nice to have a regular technical bookstore in Kendall Square. You’d think with the MIT Media Lab around the corner and the MIT Laboratory of Computer Science up the road and all the bio and other tech in Kendall Square, that would be enough…but now you have to go to the MIT Coop bookstore.

Bay Area: https://en.wikipedia.org/wiki/Computer_Literacy_Bookshops[Computer Literacy] — the granddaddy (or grandmama, not to be sexist) of computer bookstores. I may have visited the DC area store during my government contract days, but it was already in decline when I frequented the original Bay Area store (so you could blame the rise of the Internet, or decline of the Internet), as it became Digital Guru, then Fatbrain and was eventually acquired by Barnes and Noble. Which is where I get my computer books now.
