= Writing iBooks Is A Tough Business

I don’t know how anyone manages to publish an iBook. After self-publishing my collection of software development essays on Amazon and Barnes and Noble, I said (to myself) that was easy, let’s try an iBook now. After all, I was already self-publishing apps on the App Store.

But at the time, publishing an iBook required setting up a separate iTunes user account for some reason. And Apple requires an ISBN. I don’t remember how I got that, but I did create a new iTunes account, and I remember submitting the book. And…nothing.

Some years later, Apple announced iBooks could be uploaded into an existing iTunesConnect account, so I tried again. It’s still weird. Although you can log in with the same credentials, it’s a separate login from an iTunesConnect app login. And you have to upload iBooks with a separate app, iTunes Producer, which requires an app-specific generated password.

But I did all that, and…that was over a year ago.

About once a year, I log in and check that my book is indeed under review on the stores for fifty-one countries. I’d pretty much given up on it, until I got an email today saying I needed to fix something. The ticket says I need to properly format the author name, according to these guidelines.

I checked iTunes Producer and thought, what the heck are they talking about it? I entered my name the way is says to.

But then I realized what I thought were formatting instructions below the name field is actually a second field. The first field is supposed to have “Philip Chu” and the second one is supposed to have “Chu, Philip”.

This is what happens when someone decides borders are so twentieth century (and so are affordances). Lines, who needs lines?

Anyway, I’ve resubmitted the book. Look forward to it in two and half years.
