= Amazing Comic Con

I’m cutting down on Comic Cons, having missed WonderCon this year and planning to skip the big one in San Diego (they switched me from Creative Pro fessional to Trade Professional — well, I never!).

But the blood bank texted me that it’s time to donate again (and they offered a free Rubio’s taco for every “MAX” donation), and when I searched for available appointments, the blood drive at Amazing Comic Con here at the Las Vegas Convention Center showed up. So I figured I’d kill two birds with one stone (kind of an awful saying, now that I think of it), and woozily browse comics after giving blood.

Amazing Comic Con is not that amazing compared to the magnitude of San Diego Comic Con or even its mini-me WonderCon, but ther are things I like about these smaller and cozier Comic Cons, including the local representation. A number of booths featured Where We Live, the comic assembled to benefit victims of the Oct. 1 shooting. One of those was Alternate Reality Comics, my favorite local comic book store (and there are quite a few around here). They carry an eclectic collection, and I can always count on the proprietor for good recommendations.

At these events, of course there’s cosplay, and my favorites are the parents who cosplay with their kids.

Now that’s family values!
