= The Best Feedback Email

I like to think I don’t get too worked up over negative feedback, at least not as much as one author who responded to my Amazon review with a commentary on my miserable existence and a recommendation to get treated for depression (his Amazon replies have much more verve than the prose in his book).

Still, I get unduly irritated over some emails, like a recent customer who threatened to delete my HyperBowl app and leave a one-star review if he didn’t see the changes he wanted within a week (for full effect, it should have been lettered like a ransom note).

Fortunately, I’ve found most people dial it down or even switch to encouragement when they find out the evil greedy corporation (or game studio) they were trying to strike a blow for justice against is just me (and by the way, what company of more-than-one is going to update an app within a week?).

But really, the negative stuff is rare — most communication has been positive, many in the form of “thank you for making this game.” One in particular, from a couple of years ago, made me feel like this was all worthwhile and I actually made a difference:

I am a teacher of special ed students and have been looking for a good bowling game. Hyperbowl was requested by a student and he is sooo happy. He will work a whole day in a regular ed. classroom for just 10 minutes of hyperbowl. Thanks for the motivation reward!

And that, for me, is a motivation reward.
