= The Complete Book of Screenwriting

After countless hours of sitting in front of the TV and exclaiming, “I could write better dialogue than that!”, reading J. Michael straczynski’s _The Complete Book of Screenwriting_ has given me a better handle on the pragmatics of scriptwriting — the differences between TV and script formats, don’t submit entire unsolicited scripts (it won’t be opened for legal reasons), film pays better than television, and the importance of joining the WGA and getting an agent.

Straczynski doesn’t provide any convenient formulas for scriptwriting, but he does give some useful common-sense tips. Sound out the dialogue as you write — it might look great on paper but turn into a tongue-twister for the actor. Research your genre (in the case of TV, familiarize yourself with the series you want to write for). Start with an outline. Don’t set the pace too slow and thus lose the audience in the beginning.

This book is oriented largely toward television and film scriptwriting (the author was the creator of Babylon 5 and producer/writer on Murder She Wrote — I can’t wait to see the crossover episode). It begins with a history of the television and film industry that explains some of the current technological and business constraints that screen writers face, and ends with a sample episode script from Babylon 5.

But the author does include some treatment of playwriting and script writing for radio dramas and animation features. The latter is somewhat related to video game script writing — dialogue for animated characters must not rely on distinct “acting” such as gestures or facial movements. With the increasing number of video games produced with movie-like production values (some of them tied into actual movies), I hope Straczynski will some day update this book with a chapter covering game script writing.
