= https://en.wikipedia.org/wiki/Faith_of_My_Fathers[Faith of My Fathers]


It’s been a while since I read that John McCain's autobiography, but what stuck with me was his capture, imprisonment and torture for over five years during the Vietnam war and his refusal to be released for PR purposes before his fellow prisoners. It amazes me that he professes no hard feelings for most of his captors (except one sadist he’d probably still punch out if he got the chance).

I also liked how he admitted to and took responsibility for what he saw as his failings, including poor behavior as a student, the failure of his first marriage and breaking under torture to give a false confession (although obviously you can’t blame him for that).

Of course, I don’t agree with Senator McCain on all his politics (otherwise I’d be a Republican), but I admired him enough I might have voted for him in his presidential campaign if he hadn’t selected Sarah Palin as his running mate (dealbreaker). Certainly I would have preferred him over George W. in his earlier run.

The reason I’m writing this now is because this is Purple Heart Day, and it seems like an appropriate occasion to keep the word “hero” in perspective. Some were calling McCain a hero for his no vote on the Republican “skinny repeal” health care bill. Well, first he was called a hero by fellow politicans when his current cancer situation was discovered, then not a hero by those aghast at his return to vote yes on “consideration” of the Republican health care bill, and I saw one tweeter say the North Vietnamese guards who tortured him were heroes (which just goes to show there are always dumbasses on any side of an issue), and then back to hero again (and possibly Machiavellian genius), with some pointing out that actually the two Republicans who consistently voted no from the beginning were the real heroes.

Senator McCain is a hero for his service in the Vietnam War. Voting in the Senate and voting his conscience is his job, as it is for every Senator. Giving (and taking back) the term “hero” in this context disrespects the real risks and sacrifices he and others have made in life-threatening conditions and shows how far our standards and expectations have dropped.
