= https://en.wikipedia.org/wiki/Len_Deighton[Len Deighton]

I haven’t written many reviews on Goodreads, but I wrote a few brief ones on some of Len Deighton’s Cold War-era spy novels. His books are largely out of print (although https://en.wikipedia.org/wiki/SS-GB[SS-GB] was recently produced as a TV series), but I often find them in libraries and used bookstores.

https://en.wikipedia.org/wiki/XPD[XPD] is one of my favorite Len Deighton stories. I’m sure of that because I’ve read it at least three times, now. It has among the best plot twists of Deighton’s novels, but I think the appeal of this one is, atypically, the characters at the center who aren’t spies, just poor schlubs who are caught in the middle but who have a fascinating intertwined history and some strength of character and sense of morality.

Particularly, and again atypically, the American character Charles Stein, whose girth and gusto might be intimidating in person but are entertainingly depicted in the book. This story doesn’t have the first person cynicism of the Bernard Samson books but it does feature the traditional Deighton ingredients of wartime nostalgia, longtime regrets, ever-present danger and uncertainty, and a glimpse of hidden and hard world operating beneath ordinary life.

https://www.deightondossier.net/Books/Other%20novels/violentward.html[Violent Ward] is one of Len Deighton’s weaker novels — it’s as if he’s trying out an LA noirish detective voice, and it doesn’t sound natural. Also, while the story has his customary twists, it’s not as absorbing as his usual work. But the characters are interesting to the point where you (eventually) start rooting for them, throw in some sly digs at the LA and Hollywood scene, and it still makes for an entertaining read.

Len Deighton’s American characters tend to be somewhat cardboard and caricatured compared to his European ones, but in https://en.wikipedia.org/wiki/MAMista[MAMista] he does a good job in making the guerrillas in this story interesting and sympathetic, without glossing over the moral gray areas they occupy. The novel is laced with cynicism (moral and political) and ends with some neat ironic twists but the real star of the show is the jungle. The writing effectively immerses you into the simultaneous oppressiveness, beauty and danger of the environment so much that you wish you were there to see it and you’re glad you’re not.
