= https://en.wikipedia.org/wiki/Mr._Monk_on_Patrol[Mr. Monk on Patrol]

If you’re not a fan of the TV show https://en.wikipedia.org/wiki/Monk_(TV_series)[Monk], then this book may fall flat for you. Then again, you might find the characters quirky and charming. The same could be said of the TV series — the stories were just an excuse to see the characters every week. The author was one of the show’s writers so it’s no surprise that the book carries the same feel — it’s like putting on a comfortable old shoe.

The first person narrative from Natalie, Monk’s assistant, at first seems odd, but I think it’s a smart choice. Let’s face it, I liked Natalie on the show, but she wasn’t one of the more interesting characters. This choice not only keeps her from fading into the background but actually pushes her forward as a main character you’re rooting for.

There’s some closure also in getting to see Sharon and Randy together — that really felt like it was thrown in at the end of the show. So, just like one of the TV episodes, this was nice, I’m looking forward to the next one.
