:toc:

= More About Ada

A few years ago, I wrote about how a history of computer programming would feature women who haven’t received enough recognition (which in itself is a good reason for everyone to learn about the history of computers), most notably Ada Lovelace.

Since then, I’ve updated my reading, including, most recently, http://sydneypadua.com/[Sydney Padua]’s imaginative alternate-history graphic novel https://en.wikipedia.org/wiki/The_Thrilling_Adventures_of_Lovelace_and_Babbage[The Thrilling Adventures of Lovelace and Babbage].

I expected a fun read and wasn’t disappointed (how is this not a TV series by now?), but the real treat is all of the real biographical details, much of it original painstaking research, of Lovelace and company (not just Babbage, who perhaps is a cautionary tale for entrepreneurs, but also a cast of characters in their circle and of their time).

Ada also receives an entire chapter (the first chapter!) in Walter Isaacson’s https://en.wikipedia.org/wiki/The_Innovators_(book)[The Innovators], which also sketches the course of her too-short life with its unavoidably juicy details (she was genuinely a “rockstar” programmer). One point I would quibble with is Isaacson’s determination that Ada wasn’t the first programmer, based on the technicality that Babbage the hardware guy obviously knew how to program his computer (if it were ever to be built, that is).

But that’s like saying (I hope this is not too tortured an analogy) that the first car driver was the person who first invented the car. Again, technically, yes, but that’s a far cry from a professional driver (race car, Lyft…). Here’s a better and more in-depth explanation from a programmer’s viewpoint.

She saw greater potential in Babbage’s design than merely being a programmable calculator. She saw beauty in code and, as Isaacson notes, called programming a “poetical science” (fitting for the daughter of Lord Byron and humanities majors, take note, you’re missing out!). She even predated Alan Turing by a century in pondering the possibility of artificial intelligence (Turing cited her musings as Lady Lovelace’s Objection).

Isaacson’s book also profiles Grace Hopper (of COBOL fame) and the half dozen or more “Women of ENIAC”, so it would be a mistake to think of Ada as the only woman who was a key figure in computing history, but I think it’s fair to say Ada was not only the first “real” programmer, but also the first computer scientist, and I look forgot to seeing a television series of The Thrilling Adventures of Lovelace!
