= Seinfeldia

I often complain how during my few months working in New York City, people there routinely assumed I worked in a Chinese restaurant (“I’m here to pick up my order”).

But, as I was reading https://seinfeld.fandom.com/wiki/Seinfeldia[Seinfeldia], a delicious (I use this word because I just said restaurant) dive into the history of Seinfeld, I remember seeing only two Asians in the show: one was the venerable James Hong, working at a Chinese restaurant with his trademark fake Chinese accent (I was shocked when I saw him in an old sci-fi movie talking in his normal American voice), and the other was a Chinese delivery boy who made a phone call to China.

The book touches on the lack of diversity in the show just briefly but also notes that Seinfeld formed America’s view of New York and (I don’t know about this) performed a key role in revitalizing the city. So, in a way, you could say the show provided an authentic display of New York’s diversity as viewed by a segment of New Yorkers (and not the first — take all those Woody Allen movies).

It’s not just the Chinese restaurant thing. When I was working in New York, we had a meeting with Samsung America with a white American guy and an Asian American guy. Afterwords, a coworker wondered whether the Asian guy was from Korea. Sure, his name is Sam and he has no foreign accent and the other guy is American, but OK, he’s from Korea.

And I saw on twitter a Chinese-American woman announced it was an anniversary of her arrival in New York, whereupon a New Yorker congratulated her and said America needed more immigrants like her. Except she’s not an immigrant, she’s from LA.

Also on twitter, a designer who moved to New York from California said he liked New York’s authentic diversity with people from all kinds of countries building communities together, vs. the “social justice” of Berkeley types. OK, he just moved there, but sounds like New York’s more his style. Anyway, I responded that I prefer California diversity more: the type where people don’t routinely assume I’m from another country.

Like when a Manhattan museum staffer asked if I was Korean because he was thinking of buying a Hyundai and wanted some tips. Even if I was Korean, what tips would I have? Like there’s a secret Hyundai newsletter for Koreans? This is starting to sound like a Seinfeld bit. If Seinfeld was Asian. Asian-American George, Elaine, Kramer, even Newman, I could visualize it… Hey, we’ve had two sitcoms in the last twenty-five years featuring Asian Americans, I think we’re due.
