= https://www.penguinrandomhouse.com/books/309699/shatner-rules-by-william-shatner/[Shatner Rules]

I saw https://en.wikipedia.org/wiki/William_Shatner[William Shatner] give a talk at MIT back in the eighties. I recalls his enthusiasm, relating stories that surely were embellished, one of which featured some instinctual martial arts prowess that he miraculously summoned, along with a complete misunderstanding of physics (he cited the opposite of one of Newton’s Laws). The crowd loved him.

This memoir is similar, but it’s not all ham. Spanning the ups and downs of his adult life (not much about his childhood, but you get the impression that he didn’t get the attention he needed), he gets serious about his first wife’s addiction and accidental death, rough treatment by tabloids, low points of his career (living out of a car), and his ambivalence about being Kirk (interestingly resolved after meeting https://en.wikipedia.org/wiki/Patrick_Stewart[Patrick Stewart], who took his Jean-Luc Picard role very seriously).

Despite the self-deprecating bits of his narration, Shatner is obviously sensitive to the criticism of his acting and hostility by many of his Enterprise crewmates. And who wouldn’t be? But really, he should have watched a couple of Comedy Central roasts before agreeing to be the target of one, and if a lot of people who worked with you don’t like you, saying they’re just jealous and what did I do? isn’t very convincing.

It seems to me his humor is slightly homophobic, and slightly more anti-geek (hey, if you don’t like what the critics are saying, remember your fans and stop telling them to get a life). And hardly any mention of https://en.wikipedia.org/wiki/3rd_Rock_from_the_Sun[3rd Rock from the Sun]? But the guy is working hard and having fun, and it’s hard to hold anything against him. He may not be a geek, or everyman (he seems to think being broke as an actor is worse than any of us being broke), but he is Kirk.
