= Thoughts on Design

Perhaps my favorite thing about the San Francisco airport (with the food court dim sum a close second) is the San Francisco Museum of Modern Art store in the International terminal. I try to always stop there and pick up a design book that would be hard to find in my local Barnes and Noble (not to mention Crown Books, which is almost the only other bookstore where I live).

On one of my recent trips through SFO, I snagged Paul Rand’s https://www.paulrand.design/writing/books/thoughts-on-design-1st-edition.html[Thoughts on Design]. This is a small book, less than a hundred pages, largely with graphics (naturally), and it starts off with fairly general pronouncements, but there’s some good stuff once it gets going, in particular some directives I haven’t seen before, like making use of repetition, and avoid choosing a font style correlated with the subject (e.g. the cliche of “chop suey” lettering).

I wouldn’t say this is a must-have on your designer bookshelf, but, hey, it’s Paul Rand.
