= The Upright Thinkers

Aside from the first week at my junior high school, where they apparently assumed I was a poor immigrant kid who would be a low performing student and thus assigned me to classes with other low performing students, I was generally considered a “gifted” student. That came with perks like, in grade school, going on a field trip to an aquarium, and, in high school, a day spent learning how to be “creative” (some fads never go away).

It seems to me every kid would have benefited from the aquarium trip, and maybe more than the so-called gifted kids, but they weren’t missing anything with the creativity class. We listened to anecdotes on how famous scientists experienced their ephiphanies and then we ran around smashing ice cubes (is that a band name?) to see who could make water the fastest.

That time would have been better spent reading a book like Leonard Midlow’s https://www.penguinrandomhouse.com/books/223574/the-upright-thinkers-by-leonard-mlodinow/[The Upright Thinkers], a recounting of the revolutions in scientific thought.

A major message of the book is that science is a hard slog, and often it’s a hard slog going down the wrong path (much unlike the quick-fix resolutions in the MacGyver episodes written by the author, who is not only a noted physicist but a screenwriter).

For example, Newton didn’t havean apple fall on his head. Or he could have, but that would have been just bad luck.

Rather, after an emotionally deprived childhood and working essentially as a grad student without a scholarship, he spent spent thirty years burning the midnight oil on alchemy before Edmund Halley (of Halley’s Comet fame) asked him to look over Kepler’s orbital laws, and then Newton spent another eighteen months burning the midnight oil putting together his Laws of Motion.

Einstein did crank out three revolutionary theories in one year at his patent office job, (which reminds me of the recent advice I received from a retired mailman telling me I should have worked for the post office). Still, he spent much of his career futilely trying to turn back the tide of quantum mechanics.

And those are the success stories. For every crackpot theory that turned out to be revolutionary, there are a bunch of crackpot theories that are still crackpot theories and theorists who’ve only come up with crackpot theories.

So there are no easy answers or shortcuts to success. Instead, there’s hard work and perserverance, good luck, and being in the right place and the right time. And being born in the right place and right time, and right gender (there’s a reference to Lise Meitner, who co-discovered nuclear fission but missed out on the Nobel).

But overall the book is an optimistic one, profiling those who were dedicated to their intellectual passions and eventually rewarded with brilliant insights, and overall furthering the march of human progress. And the author’s bio reminds us that, whatever your main job is, don’t give up on your bookwriting and screenwriting aspirations.
