= Marissa Mayer and the Fight to Save Yahoo!

Prior to reading this book by Nicholas Carlson, I’ve only seen the snippets criticizing Marissa Mayer’s performance at Yahoo and reactions that the book is a hack job. However, I found the author’s treatment to be fairly balanced, pointing out the early progress she made and the major role she played at Google

Frankly, I found the account of her career at Google and the assorted politics there more interesting than her fewer years at Yahoo, but despite its title, this book is not just about the Mayer era at Yahoo — it covers Yahoo’s history and the succession of management there from its beginning, which is fascinating and convincingly poses the question what Yahoo’s role really is and can the company be saved if the question of its relevance can’t be answered?

The book is only slightly blemished by a few incongrously put together sentences where I wondered exactly what point the author was making, and a light touch of the common male tech writer’s tendency to mention womens’ hair color and men’s only if they don’t have hair. I counted two blondes and three bald men. Meyer is one of the blondes, of course.
