theme: jekyll-theme-minimal
title: Technicat on Software
description: essays on software development
show_downloads: true
logo: /images/dakotasnow/CatGraphic300x300.jpg
amazon: https://www.amazon.com/Technicat-Software-Philip-Chu/dp/1082483958
