theme: jekyll-theme-minimal
title: Technicat on Software
description: essays on software development
show_downloads: true
logo: /images/icons/cat/catglasses.svg
book: https://www.amazon.com/Technicat-Software-Philip-Chu/dp/1082483958
