= Goodbye, Goodreads

Now that I’ve disentangled myself from Facebook, my next target is Amazon, especially considering their recent firing spree.

It’s not easy shedding a big tech entity. I had no problem unfriending all my Facebook friends, but Facebook pages were actually useful for my app support, and I was also on Whatsapp and Instagram.

But after a couple of years that’s all done now (although I still have an Oculus Rift hooked up to my PC). I’ve started the process with Amazon by unpublishing HyperBowl from the Amazon Appstore (the revenue was down to two dollars a month, but hey, two dollars…)

And today, I got rid of Goodreads. I joined twelve years ago in their early days, but even then I was annoyed when they introduced one of those all-encompassing indemnification clauses (the founder did personally reply to my complaint, explaining their lawyers told them to have that clause and everyone else has it), and of course their acquisition by Amazon was depressing.

Goodreads is pretty handy when I’m book browsing to check whether I’ve read a book already and how are the reviews, and the app is pretty slick with it’s camera book-cover recognition feature, but as I discovered after recently rereading Cryptonomicon, if I can’t remember reading the book, I might as well reread it, and I can always google for reviews (Google is not yet on my big tech hit list).

But, like discovering I’ve already read this book, I realized I’ve tried deleting my Goodreads account before. The problem is I have an author account, and the usual instructions for deleting an account from the web site don’t seem to work in that situation. The trick is to delete your account from the Goodreads app. Now my user profile is gone (although the author profile remains).

The next step in my de-Amazonifying campaign is to unpublish my self-published book. I hate to lose the reviews, but anyone can still buy it on bn.com, Apple, or download it free.

I doubt I’ll completely get rid of my Amazon account, because I do want the option of buying stuff there (although I’ve moved to buying books on bn.com and my local indie bookstore, and I try to buy direct in other cases when possible, like my recent cloth mask purchase). If you do buy from Amazon in these hazardous times, try to stick to the important stuff.
