= Lovely Email
technicat

When I got rid of the Facebook pages I was using for app support, I reluctantly added an email support link to my Talk Dim Sum app (reluctantly, because I’ve received so much spam from the app support email addresses for my games), but actually I got some good feedback on it, including this one today:

______________________________________________________________________________
Just writing to thank you for your wonderful dim sum,
etc photos that have to do with a chinese meal.
It brings “brightness” to my life.
In this trying times…sheltering at home…
I love looking at your photos and the lessons that go with it!!!
And your app was FREE!

Hope you are healthy and safe!!!
______________________________________________________________________________

During normal times I think, realistically, I’m doing this stuff for fun and in the greater scheme of things it’s not all that important. Especially now it seems inconsequential compared to people actively combating the pandemic. So it’s nice to know I’m helping to make someone’s stay at home a little bit better.
