= In Space, No One Can Hear You Scream…If You’re Chinese

I wrote this several years ago — since then, the Expanse is another series that does silent (and weightless) space right, and I’ve read that the Chinese in Firefly was originally supposed to be Cantonese, but one of the translators gave them Mandarin and they didn’t notice. Also, the Tams were originally going to be at least part Asian, but they didn’t follow through on that.

I recently read Serenity Found, an enjoyable set of essays on on Joss Whedon’s Western sci-fi depicted in the TV series Firefly and the movie Serenity. Firefly is probably my second favorite TV series, next to Buffy the Vampire Slayer, for the same reasons as as everyone else — the characters, the humor, the writing, the visual effects and colorful vision of the future.

But none of the essays mentioned that in the Firefly universe, space is silent! I can’t think of any sci-fi on film since 2001: A Space Odyssey that didn’t allow sound (big booming spaceship and space weapon sounds) to travel through vacuum. Even the makers of the new Battlestar Galactica briefly considered showing silent film space battles but fell back on the traditional noisy dogfights. Now, it would have been nice to see the Firefly crew floating around their vessel, but I understand television production budgets don’t allow for zero-gravity studios, yet.

The aspect of the Firefly universe that really bothers me, though, is the nearly complete absence of Chinese. Now, Joss Whedon’s Sunnydale is no worse than Woody Allen’s and Seinfeld’s Manhattan (although the complete absence of Latinos in Sunnydale, CA is pretty weird). And when white Hollywood screenwriters force the issue and try to go ethnic, the results are sometimes not pretty. Daniel Dae Kim was great as one of Wolfram and Hart’s slimy lawyers in Angel, and I liked the Asian girl in the first Buffy alternate universe episode who ends up on an automated blood-sucking conveyor belt, largely because they weren’t Chinatown demons, exotic hotties from another dimension or Chinese potential slayers complaining loudly in Mandarin about lactose intolerance.

And while I’m at it — how did Crash get an Oscar? A movie ending with illegal alien Chinese smuggled by greedy local Chinese are “rescued” by a African-American carjacker who responsibly dumps them in Chinatown with a a few bucks for noodles. He couldn’t have dropped them off in Irvine?

But I digress — the Firefly crew routinely curse in Chinese, which is cute (as much as the pronunciation is awful — and I speak awful Chinese, so I know). The Sino-slang ostensibly stems from an Anglo-Chinese expansion into space. Yet where did all the Chinese go? Two of the Firefly crew have the last name Tam (brother and sister) and have dark hair. Are we to infer that all Asians intermarried with the Anglos enough generations that in the future no Asian actors will be needed? There is one episode — count it, one — where a group of rural Chinese are dancing outdoors. They have no speaking parts, so I guess the future only has room for Chinese extras.
