= Crushing It, for Introverts

There’s a lot of encouraging advice out there, but it’s mostly packaged for extroverts: Crush it! Network! Find a mentor!
Be a mentor! Meet up in meetups! Game jam in game jams! Get out of your comfort zone!

But a little socializing lasts me quite a while, like with camels and water, and I’d like to think we don’t all have to operate like we just downed a six-pack of energy drinks just because that’s the conventional, or louder, wisdom. So I’d like to offer some alternative advice, without exclamation marks (imagine hearing this in a soothing Malcom Gladwell podcast voice).

No need to crush anything. Just enjoy the journey and learn.

You don’t have to seek out a mentor, as if it’s the key to success. Forgo the ass-kissing and just focus on doing good work and being a good person. The mentors will come to you. Besides, there’s the Internet: why limit yourself to one source of questionable wisdom when there’s a whole world full of unsolicited advice — take the stuff that sounds right to you and ignore the rest.

And you don’t have to be a mentor. It’s not like you’re getting paid for that time, and why should anyone have exclusive access? Again, there’s the Internet: you can broadcast your pro tips to the world, or at least your Patreon subscribers.

Meetups are a great way to meet people face to face, but they’re still meetings. A three hour meetup, plus travel, is a big chunk of time you could spend doing something else, like working on your project, studying, blogging like I am right now, napping… I like to split the difference by browsing for interesting meetups, attending them once, and never showing up again. I feel it gives me a competitive edge. Same with conferences — that’s a week others are partying while you’re getting work done, so don’t feel bad about not going to GDC!.

Speaking of games, there are critics of game jams, but I’m not one of them. I like the concept, and I’m impressed with the resulting games. But I have no interest in participating in one. I’m not a group sprinter. I’m a solo marathoner. I don’t even like ride-sharing. Again, a three-day game-jam is three days I could be spending on my own project, on my own schedule.

So, basically what I’m saying is, sure, you could get out of your comfort zone, but speaking for myself, there’s still a lot of unexplored territory in there, and I rarely feel the need to leave it.
