= 徐宏恩

That’s my https://en.wikipedia.org/wiki/Chinese_name[Chinese name], and I’m writing this mostly so I can remember it and I can better play the “What’s your Chinese name” game when I go out for dim sum.

I’ve always had a copy written down, but what’s happened over the years is I’ve found a ratty copy of my name and then retranscribed it on a fresh piece of paper, and because I don’t actually know how to write Chinese characters, after a few iterations it becomes gibberish.

But I recently found a correctly written version, probably provided by my mom, and this time I got it onto my computer via a torturous sequence involving the camera and handwriting features in Google Translate, as I don’t know how to use a Chinese softare keyboard, either.

I think I can be forgiven for not remembering my surname 徐, as the English spelling of my https://en.wikipedia.org/wiki/Chinese_surname[surname] Chu is not particularly close to the Cantonese pronunciation “chèuih” or the Mandarin pronunciation “xú” (my dad told me people in mainland China also had trouble figuring out his name).

徐 is not one of the https://en.wikipedia.org/wiki/List_of_common_Chinese_surnames[top ten Chinese surnames], but it is number eleven, and the same name as the Hong Kong filmmaker https://en.wikipedia.org/wiki/Tsui_Hark[Tsui Hark], so that helps.

As for the rest of my name, which is used as my English middle name, the English spelling “Hung-en” bears only a vague resemblance to the Cantonese pronuncation “wàhng yān” but is pretty close to the Mandarin pronuncation “hóng ēn” (which is weird since my father’s side of the family is Cantonese).

My mom said they made a slight mistake choosing that name, should have been something slightly different. I’m thinking it might have been 宏願 (wàhng yuhn in Cantonese, hóng yuàn in Mandarin, means “great ambition”), but I’m just guessing. Anyway, my current name is on my drivers license and other docs, so I have no plans on changing it.

Although enough people misspell my first name “Philip” (bankers and baristas: somehow it often turns into “Phillip” on my bank statements and I’m amazed when I see “Fil” or “Fill” on my coffee cup) or see I’m Asian and start calling me “Chu” as if it’s my first name (or only name, like “Cher”), I think, well, maybe renaming isn’t a bad idea.

For example, someone thought I was “Dan” the other day and I tried it out in my head for a while, Dan, Danny, Daniel, Daniel Day-Lewis, Daniel Dae Kim. Not bad. Keep ’em coming.
