= The Only Good Statue Is A Dog Statue

There has been a lot going on with statues, lately. There are some long, well-reasoned responses to those who ask, rhetorically, if we remove all Confederate statues, what about those slave-owners, Washington and Jefferson?

I have a shorter and simpler answer: it’s fine with me if I never see a statue of Washington or Jefferson. I don’t think we should have statues of politicians (much less have their heads blasted into mountainsides), even long-dead revered ones. It promotes (literally) oversized and glorified images. We shouldn’t be worshipping historical figures — we should be learning about them, the good and the bad, and what they did, not just what they said. Most of the founding fathers were slave-owners. FDR signed an executive order sending 120,000 Japanese-Americans into desert prison camps.

When I visit Washington D.C. I just want to see the museums, I can do without the statues. The only statue I’ve ever made a point of visiting is the famed statue of Hachiko at Tokyo’s Shibuya Station, because that story always gets to me, and dogs, what’s not to like? I’m pleased to just recently learn there’s a new statue showing him reunited with his master, who he waited for at the train station every day for years after his master’s passing.

Hachiko’s story has been made into a Japanese film and an American one starring Richard Gere (which might be a fine movie, but I’ve avoided it because it reeks of the Last Samurai “this would be great if it just had a white American movie star”), but my favorite depiction is a Futurama episode, Jurassic Bark. It’s the saddest thing I’ve ever seen on TV.
