= What’s Your Ancestry?

I filled out my census form online yesterday and it was quick and easy, not as long as I remembered it being in previous years. Kind of like a dating interview, actually: “So…you single? Own your own home? Living with anyone?”

But the question that always bothers me is the one about race (I suppose that could come up in dating interview, too). It reminds me of my encounters with New Yorkers who want to know “What’s your race? Asian? What kind of Asian?”

I get the importance of making sure the makeup of the population is properly recognized and resources and attention properly paid. But simply saying “race” is so ill-defined and unscientific (and mailing everyone a question about it just encourages them to do the same). I answered “Chinese” but I don’t think of Chinese as a race. I do think of nineteenth-centry bigots like Al Swearengen referring to Chinese as a race, and worse.

I checked my 23andme account and they don’t use the word race anywere that I can see. They say “ancestry” and that sounds right to me. When people (again, a lot of New Yorkers) ask my race or nationality or where I’m from or really from, what I’m waiting for is the word “ancestry”.

And even then, a one-word answer is going to be too simplistic. Notwithstanding my census answer, according to 23andme I’m mostly Chinese, but I have Elizabeth Warren traces of several other groups.
Image for post
Image for post

So I wish the census form would ask for ancestry instead of race, and I wish I could just submit my 23andme report. Maybe one day the census form will just ask for a cheek swab.
