= A Question They Couldn’t Answer

After twelve years of living there, I miss some aspects of Huntington Beach, like the beautiful beaches and the excellent public library, but as one of my friends advised me before I moved there, “It’s really white down there.” And this was a white guy.

Now, as in much of California, Huntington Beach is reasonably diverse, and I didn’t get all the “Where are you from?” queries I got on the East Coast (Or they would say “I’m here to pick up my order” if they saw me in a Chinese restaurant).

But look at the Huntington Beach Centennial video on the city web site. Well, don’t look at all of it, it’s nearly an hour long, and I mostly lay on the couch napping as it played on the local public station, but around the twenty-six and a half minute mark, it veers from the usual fluffy history and devotes about forty-five seconds to the Japanese-American internment in World War II.

My reaction during those forty-five seconds was pleasant surprise that they were actually covering the topic, then dismay. Not only is the sheer scale of the internment not mentioned (over 100,000 Californians), but the interned are only described as “immigrants” and “residents” which is not just misleading but mostly false, as most of the interned were American citizens and 80,000 of them where American-born citizens (that’s why it’s called the “Japanese-American internment”).

And the internment camps are called “relocation centers” which sounds like a stay at the Howard Johnson. I’m not a fan of the term “concentration camp”, but surrounded by barbed wire in the desert with armed sentries? Closer to the mark. There’s no detail of their lives after being rounded up — the only human interest here is a woman who lost a potential boyfriend because he was sent away.

Worst, the question of their loyalty is described as “a question they couldn’t answer.” Really? I guess if we ever have another military conflict with China, I should start packing my bags. And considering some ancestors on my father’s side were Muslim, I’m doubly screwed (a woman in New Jersey explained to me that Obama is Muslim because his father’s Muslim, but assured me I’m OK, because “You’re not a terrorist, right?”).

Well, maybe they can work on answering that question in the Huntington Beach schools, since that video is now classroom material, as I was informed by the city when I complained (one thing about Huntington Beach is the city does respond quickly to inquiries, even if it’s government bureaucracy doublespeak):

[quote]
Thank you for your thoughtful comments regarding the history video. I know we tried to include it as part of the history of Huntington Beach. I will share your concerns with others in leadership in the community. The program is featured on our government channel, website and was shown on KOCE. We have also distributed hundreds of copies to individuals, middle schools and high schools. Yours is the first “negative” comment we have received and I can assure you people of all different backgrounds have viewed the video. Thanks again for your input.

So the schools and city hall may be a lost cause, but at least the library stepped up. During that centennial celebration period, they hosted a series of talks including one delivered by someone born in one of those internment camps, who noted a local Japanese-American soldier who had died in combat was prevented from being buried back home until intervention by Ronald Reagan (who later signed the redress act for the interned).

Now, you can listen to George Takei talk about his internment childhood, and if you’re in LA, visit the Japanese-American National Museum (and check out Little Tokyo while you’re there). On the Internet, just googling “Japanese American internment” will provide a variety of sources, from wikipedia to PBS to the National Archives, which is something the writers and producers of this video could have done, even in the dark ages of 2008.

It’s past time to remove that video from the city web site (and hope that the schoolteachers aren’t showing the DVDs, anymore), or at least dust off their video editing software and excise forty-five seconds. And from now on, if you’re going to make a historical fluff piece, stick to the fluff.
