= The Best Places to Live

Many of my classmates from Iowa City West High School (which by the way is a really convenient name, as I found some document frames at Staples already containing a “West High School” diploma) still live in Iowa City, and a few recently noted on Facebook that Iowa City is #3 on this list of 16 Best Places to Live.

Setting aside that the article shows only white people living in all those towns (to be fair, not every photo shows a white person — there is an almond croissant and a couple of crabs), I do have some fond memories of Iowa City.

For one thing, I remember in downtown Iowa City, drivers would always stop for pedestrians crossing the street, wherever they happened to cross. So it’s a miracle that I didn’t end up on a windshield when I went to Boston for college (that actually happens to a few freshmen crossing Mass Ave. every year). And once as I trudged to school, an elderly man stopped and offered me a ride, which I took. Around here, that would result in an Amber Alert.

Of course, it’s been a while, and things may have changed. But I suspect not a lot. When I drove back there for my tenth year reunion and stopped at a truck stop for breakfast, my brain misfired and I requested hash browns instead of the corned beef hash that I intended to order. The waitress asked “Just hash browns?”, and when I confirmed, returned with a mountain of hash browns, enough for more than a meal. The bill was $.99. I suspect she figured I was a starving foreign student (this was 35 pounds ago). Anyway, best plate of hash browns I ever had.
