:toc:

= Yeah, I'm Introverted, Now Leave Me Alone

During a childhood camping trip in Catalina, while all the other kids ran off to the beach, I sat at a picnic table, went into library mode, and settled into a good book (can’t remember which one, but I was really into Heinlein and Asimov back then).

Later that evening, a camp counselor asked me if I was unhappy or having problems with the other kids. Apparently, a well-intentioned elderly couple saw me sitting by myself and alerted the counselors, and they all had some trouble believing a kid would like sitting by himself and reading.

So I was pleasantly surprised by the popularity of Susan Cain’s book and TED talk on introverts. I still haven’t read the book, but I watched the talk and read many ensuing interviews (part of my surprise is just seeing an introvert be such a successful public speaker and interviewee).

I suspect the attention is due not just introverts seeing their story publicized (there aren’t a lot of introvert conventions — well, maybe Comic Con), but also non-introverts finally getting a handle on those wallflowers who never want to join the group for lunch (guilty). Kind of like discovering a new species…fascinating.

Now, to gripe a bit, the problem is that now people like to call themselves introverts, just like it’s been fashionable to say you have OCD, Asperger’s, and wheat allergies. At least, that’s what I’ve seen talk show guests say, like “I have OCD — I always have to make sure my kitchen cabinets are closed”. And just look at Whole Foods. That’s a whole lotta well-heeled folks with a gluten grudge.

If you call yourself an introvert because on occasion you don’t feel like partying, that’s like calling yourself anorexic because you settle for a salad once in a while. If you’re really introverted, then at parties you feel like the Tim Robbins character in Jacob’s Ladder:

Speaking for myself, it’s not that I’m not social. There’s just a limit. A three-hour limit (I’ve timed it). And no crowds (I spent six months in Hong Kong waiting for the food court quiet hours — lost five pounds). If I had a video game energy bar above my head, you could see it draining at every GDC party I’ve attended.

But a quiet drink or meal with one or two friends, no problem (two is possible as long as neither of them are too extroverted — otherwise the two’s company, three’s a crowd rule applies).

I’m not bragging about being introverted. Aside from the social aspects, professionally it has its disadvantages. A total aversion to meetings is not really better than being one of those sickos who enjoy calling meetings (yeah, I’m talking to you, scrum masters…)

But given that introversion is almost trendy, now, I don’t feel like the Steve Martin character in The Lonely Guy:

And I get a lot of reading done.
