= Unity Connect Is The LinkedIn Of Unity, But Better


Sure, Unity 2017 looks great, but the newish Unity product that I really like is Unity Connect.

It’s basically a LinkedIn for Unity developers, except I hate LinkedIn and I really like Unity Connect. There’s no recruiter spam (yet), mobile advertiser spam (yet), people wanting to connect just to ask you a question (yet). And it’s better looking than LinkedIn, even the resume portion.


But where Unity Connect shines is the project section, which acts as your portfolio.

Each project entry lets you upload images and list youtube and sketchfab links, and displays App Store, Google Play, and Unity Asset Store badges. Aside from the Unity Asset Store badge, it’s general enough I use it to display all my recent work (the apps displayed above are Swift and Objective-C apps).

This is actually the portfolio site I’ve dreamed of implementing. A fundamental problem I see with LinkedIn is that it assumes a network consisting of coworkers in jobs. What I really want is a network of people who’ve worked together on projects. Like a social mobygames.

To take advantage of this in Unity Connect, I’ve started moving my projects over to my company profile.

After posting my project there, I add myself as a contributor and anyone else on Unity Connect who worked on it (I found one other HyperBowl developer who’s on Unity Connect).

This isn’t an entirely new idea (one of the Scaleform sales people who screwed me over there later tried to LinkedIn connect to me to announce his social portfolio site startup). But it’s the first time I’ve seen it in action, and it’s looking good.
