= Turning 50

Well, I normally don’t announce my birthday, deadened as I am to all those Facebook notifications, but turning 50 (yesterday) is a milestone of sorts in our base 10 society. For programmers, maybe 48 or 0x30, should be more meaningful. Regardless, I don’t feel older, or wiser, or even more mature. It does seem other people are getting more immature, but I guess that’s just relativity in action.

Physically, I do feel I’m getting older, the worst part being my eyesight. It was always bad, and at least with modern technology my glasses are much thinner and lighter than the coke bottles I wore as a kid. But now in libraries I look longingly at the big print section, which reminds me that I now qualify for AARP membership (and in five years, the senior meals at Denny’s!)

It doesn’t help that according to conventional wisdom in the Logan’s Run world of Web 2.0, I was over the hill fifteen years ago, and apparently forgot to retire.

Of course, every generation (however artificially demarcated), considers the previous generation obsolete, so youthful disrespect is just karma. I remember when I mentioned my Dad was middle-aged, and he asked, “What do you think is middle age?”, I guessed 30 or over. But I was in grade school.

You can’t entirely blame the young for drinking millennial kool-ade (every generation’s graduation commencement speech exhorts “You are the future!”), especially considering who’s serving it these days— old rich people who go on and on about the importance of young people, like this latest bit from Paul Graham (he’s not really old, he’s just old like me). Now they’ve created a monster.

What can us other oldsters do to fight back? Bore the crap out of younger people by telling stories of “the old days” when we used floppy disks and modems. But that can backfire, as one twenty-something asked me, in all seriousness, “There was a Silicon Valley back then?” (maybe this is a problem with the tech industry, if a sense of history is disappearing)

Another time-honored form of punishment is to dispense unsolicited advice, which features the double-whammy threat of being boring and also potentially bad advice. So here’s mine:

When you’re young, you spend a lot of time trying to decide what you want to be. You should spend more time deciding who you want to be. And by who you want to be, I don’t mean you want to be a Steve Jobs wannabe. Think about what kind of person you want to be, even if you’re not rich and famous (being a rich and famous asshole sounds like fun, just being an asshole, not so much…)

And figure out who you are. It’s like finding yourself, but without the wishful thinking. There’s no need to obsess over it — there’s a fine line between being self-aware and self-absorbed. But it does get easier over time because you have more data. Then you can think about how to get from who you are to who you want to be and if it’s worth the trip (if only there was a Google driving directions feature for that…)

I found once I hit middle age, I didn’t care as much about what I was supposed to be or where I was supposed to be in life (there’s a Joe Haldeman snippet somewhere that better articulates getting more comfortable in your skin). I used to think I would get more patient as I get older, but the reverse has happened. Among other things, I don’t have the patience for is pretending I’m something I’m not, even to myself. This, by the way, does not go over as well as it should during job interviews — people just act confused when I tell them what I’m not good at or what I have trouble seeing myself doing (sorry, Google Evangelist position).

This may all sound limiting, but it’s actually freeing. When I was in high school, I talked about being President and a millionaire, someday (I don’t remember in which order), but the closest I’ve come to politics is a stint on my homeowners association board, and I could only tolerate that for three months. As for being a millionaire, well, a million isn’t that much, anymore, but it would still be nice (anyone who complains about the problems that money brings, well, it’s a reversible problem — just spend it all on kickstarters).

It goes to show those early plans weren’t that useful — better to take an Agile approach, which in my case involved going with the flow, taking a variety of different jobs to pay the bills (see, I’m putting a positive spin on not achieving millionaire status), and then eventually going freelance. If I had picked an early track and stuck to it, I wouldn’t know how much fun it is to create and self-publish games and apps, for example. Which, by the way, is something that is much more feasible now — when I first started programming, games were published by sending out floppy disk. Oops, sorry, I’m telling floppy disk stories again…

Anyway, it seems for many, this stage of life marks the beginning of Act II. I met a civil engineer who retired at 50 and goes to Comic Con every year (if you are going to pick an early track, make it something with a sweet retirement and pension plan). I know people who went back to school for their PhDs at this age, one of who went on to create a startup I’m doing some work for. My sister (a bit younger than me) is enjoying a fairly new and surging career as a comic book writer. I’ve read about people cashing in their retirement funds to start up their dream bakery, or whatever. Now that takes guts (and makes you wonder if risk management skills improve with age).

I’m not planning anything that drastic, but given that this is just halftime, maybe I shouldn’t be dispensing life advice. Which leads me to my last bit of advice, don’t take anyone’s advice. You can still learn from others, but as with politicians, don’t just accept what they say. Instead, watch and learn. And I’ll get back to you in another twenty-five years.
