= The Man In The High Castle


When I fly, I take it as an opportunity to get in some reading, and I try to pick up a book at the airport, especially if the airport has a real bookstore. Even better, a bookstore that has a science fiction section, like the Warwick’s at San Diego (the only other airport bookstores with a scifi section I can think of are in San Francisco and Portland).

So on my return from Comic Con, I chose The Man in the High Castle, which I read a long time ago, pretty much forgot, and meant to read again after watching the TV series.

I remember I found the book interesting but not particularly compelling at first reading, but either due to age or the current administration I found it more absorbing this time around. It’s not the only alternate history in which the Axis powers won World War II, but it is the most bizarre, extreme, and yet surprisingly still believable one.

The thing about Philip K. Dick stories, however, is that it’s hard to get invested in the characters, so this is one of those cases where if I had to choose between the novel and screen adaptation, I’d choose the latter, even though it’s a very, very loose adaptation. Really, the series just takes the alternate history premise, borrows some of the characters and makes them more nuanced and sympathetic, omits the pervasive mystical use of the I Ching, and thankfully avoids some of that weird Japanese-English talk (and thought) used in the book.

I mean, when PKD writes Nazi dialogue and thought processes, they sound like Joe American (including the Nazi named Joe). But the Japanese characters are written the same way sci-fi writers might write aliens. By the way, I have this issue also with Blade Runner (the movie, not the original story), which despite its fascination with Asian culture just uses it as a backdrop for a story about white people (and white androids).

The TV version of the Man in the High Castle, on the other hand, (I don’t get to say this very often) has a lot of great Asian characters (it would be bizarre if it didn’t, considering this alternate history takes place largely in a Japanese-occupied West Coast, but hey, look at Firefly). In particular, Cary-Hiroyuki Tagawa was amazing and his performance and role carried a good portion of the show. There was even a Japanese-American member of the resistance and a mention of Manzanar, which almost felt forced (but hey, the Japanese-American internment did happen, and apparently also in that alternate history).

One complaint I have about the TV series is that I felt it kind of ended on a Hollywood note where they sort of explained that everything tied together through the goodness of the heroine, which made no sense, whereas the book ended more on a “What the…?” note. Which in a story like this, makes more sense.
