= How Long Does It Take? Read the Postmortems

When I try out new mobile games, the first thing I look at is the credits screen, to see how many people worked on it. Even better are the postmortems on gamasutra — I skip to the end of each to see the personnel count and the project duration. A few years ago, I did a search for “postmortem” on gamasutra and this is the data I got from a quick scan for iOS projects:

    2/1/2012 — Spellcraft School of Magic — 6 months, 6 contributors
    11/2012 — Animal Legends-7 months, 7 internal developers +”a few” external contractors.
    1/12/2012 — Bam fu — 5 months, 2 programmers, 1 designer, 1 business person, 4 contractors
    6/22/2011 — Casey’s Contraptions — 8 months, 1 programmer, 1 artist,
    12/15/2009 — Top Gun — 4 months, 6+ developers

The team size may vary, but based on this, I wouldn’t schedule any significant new mobile game project under six months, and I expect that to increase over time as hardware capabilities improve, more social gaming and monetization doodads are required (the price of “freemium”), player expectations increase (where’s the postmortem on iFart?), and more device support is required (Top Gun was only for the iPhone — now you have a few generations of iPhones and iPads to target).

This was just a crude search — a more careful one reveals many more articles that provide similar information, so really, if someone tells me they can have Angry Birds success for $5000 (this really happened to me at E3), then someone didn’t do their homework. And we haven’t even talked about marketing, yet!
