= Feeling Flutter

This is the year I seriously started working on native Android app development, prompted by occasional queries about when I’m going to come up with an Android version of Talk Dim Sum.

Pretty much the first half of the year was spent dithering on what framework to use. I have nothing against Java, but I’ve been using it since this guy arrived on the scene
Image for post
Image for post

and I always want to learn some new tech. So I planned to use Kotlin, which has some similarities to Swift, but at the time Android Studio kept complaining about Kotlin plugin incompatibility. Then I decided to look at React Native which I kept hearing about, and while Javascript isn’t that new or exciting either, it’s actually pretty useful to keep up with, and I really liked the efficient command line compile-and-run flow.

But while React Native is good for accessing remote resources and clever at compile-time detection of referrals to bundled assets, it’s not that convenient for arbitrary runtime access of bundled assets the way I do in Talk Dim Sum.

Then I saw someone on twitter ask for opinions about whether to try React Native or Flutter, and I decided to try that Flutter thing, and I like it. It’s an open source Google framework and uses the open source Google language Dart, which I gather is a failed competitor to Javascript.

As with React Native, Flutter has a nice command-line dev flow (you can use Flutter with Android Studio, but I found I really don’t like working in Android Studio, which is why even after I got Kotlin working, I didn’t stick with it).
Image for post
Image for post

And they do an exemplary job of providing detailed error messages.
Image for post
Image for post

As one would expect from a Google framework, Flutter provides Material design support, although it’s a cross-platform framework and supports iOS builds, too. In fact, Flutter actually renders its own versions of native widgets, and, similar to Views in SwiftUI, a user interface in Flutter is a nesting of widgets. This is the Flutter body of a dish screen in Talk Dim Sum, a center layout widget containing a column widget stacking an image, text, and tortuously mapped horizontally laid out list of tag widgets.

body: 
 Center(
        child: 
          Column(children: <Widget>[
                  DishImageWidget(dish: dish),
                  DishWordWidget(dish: dish),
                  Expanded(
                    child: DishDescriptionWidget(dish: dish)),
                  Wrap(children: dish.tags.map((tag) =>          Word.words[tag]).where((word) => word != null).map((word) => TagWidget(tag: word)).toList()),
 ])));

Image for post
Image for post

Unlike Swift UI, which just has your basic Views so far, Flutter has pretty good coverage of various widgets you may need, like the tag widget above, and the grid and search widgets below. Some widgets, like the google maps widget I’m trying out now, are in a preliminary state, and technically all of Flutter is still in beta, but I’m hoping to get something out by the end of the year on Google Play. Stay tuned!
Image for post
Image for post
Image for post
