= The Key Ring to Success

I keep getting a promoted tweet from MentorBox claiming “The average CEO reads 60 books a year. That’s the key to success.” That’s hard to believe, and MentorBox isn’t actually advising you to read 60 books a year but instead to subscribe to their service to get the Cliff Notes to Success. So what they’re really saying is the key to success is taking shortcuts and cheating.

But I googled for a second opinion, and there are varying opinions on the key to success on BrainyQuote. The key to success is:

    Happiness
    Education
    Preparation
    Failure
    Honesty and loyalty
    Focused, hard work
    Mental, emotional, spiritual, physical growth
    Humility
    Individuality
    Action, perseverance
    Focus on things you desire
    Creativity
    Discovering your innate power
    Finding good partners
    Willpower
    Passion
    Work/life balance
    Positive thinking
    Being a good listener
    Management
    Ownership
    Our relationship with Pakistan
    Marry a guy who will share responsibility for the house and kids

and blah, blah, blah, there’s more. My contribution: the key to success is realizing there’s no single key to success.
