= Social Panhandling

Lately I’ve been reading some articles here on Medium that I find interesting enough to hit the Recommend button…until I reach that last line saying, typically, “If you like this article, please click on the Recommend button so others can enjoy it.”

Part of my reaction is just a tendency to balk at being pressured (one more reason I enjoy self-employment). However, I do think it’s annoying. Not as annoying as the most-of-you-won’t-share-this Facebook shame-intimidation posts, but there is the implication that if you don’t hit that Recommend button, you are somehow depriving others of the enjoyment provided by this article.

Even without that burden of responsibility, it’s just undignified to plead please recommend, please share, please retweet…that’s not marketing, that’s begging. Neither Don Draper nor Steve Jobs closed a presentation with “Please buy this product. It would really help us out.”

Plus, if you ask can-you-spare-a-share on some posts and not others, are you saying, nah, don’t bother sharing those other posts? If you consistently implore at the end of each post, well, it takes up space and gets repetitive, which is why the social site places the share/recommend/retweet button right there, but not a sentence explaining the benefits of clicking it. This isn’t Social Media for Dummies.

But if you feel compelled to entreat, you should deal out the treats. I was pestered by one Unity Asset Store vendor repeatedly to write a five-star review for the package I purchased. When I agreed and mentioned it would be nice if he would do the same for my free packages, he agreed and never did. Just the pestering is enough to deter me from being a repeat customer — the sheer laziness in reciprocity seals the deal.

If he was thinking ahead, he would have checked out and rated my products before asking the same. Then it wouldn’t have been a favor. But there’s no need to be so calculating. Review unto others, and so on. As in other professional networking, don’t just be a taker — if you’re a generous sharer, referrer, recommender and retweeter, you will reap the rewards, and the retweets, without having to ask. Save the campaigning for your next kickstarter.

And by the way, if you like this article, please click the Recommend button so others can enjoy it. Pretty please, with sugar on top.
