= Hearts vs. Stars

I’m surprised at the kerfuffle re twitter’s change from stars to hearts. On the WordsEye app, I switched from stars to hearts a few months ago, for the following reasons:

It looked better, particularly a red hearts on the (now trendy) white background. A yellow star on the (formerly trendy) black background looked nice, but wed out on a white background.

Hearts are warm, stars are cold. Thumbs up are in between (and thumbs down are mean).
Stars for likes can be confused with stars for ratings. The 1–5 star system still dominates on the App Store and such.
It’s mostly hearts and thumbs out there, with hearts dominating. Just a quick sample from one screen of my iPod touch shows flickr using stars, artstation using thumbs, and medium, ello, instagram, pinterest, and flipboard using hearts. Hearts for the win.

So for a new app, hearts are obvious. I can see since this is a change to an existing app with a ton of users, someone’s not going to like it. I think this is compounded by the previous term “favorites” instead of the new and conventional replacement, “likes”.

I was never clear on what it meant to “favorite” a tweet, so I only started favoriting tweets recently, first to bookmark tweets that I wanted to reference later, then to indicate I liked a tweet, but not enough to retweet it, or if I happened to be using the twitter app on Android, as their star placement made it easy for me to hit the star icon by default with my thumb while browsing the feed. With the new icon and terminology comes clarity. I “like” it.
