= Conversations with Creators (not Creatives)


I’m really enjoying Wil Wheaton’s Conversations with Creators, episodes downloadable free on the Playstation Store. The first four conversations have been with various prominent game studios, including one of my favorites, Bungie (in the video above).

I’m also glad it’s conversations with “creators”, not “creatives”. I’ve seen the latter so much in print and CNBC-style segments that I’m actually surprised to see the former. Calling a person a “creative” rubs me the wrong way not just because it strikes me as just one more mangling of the English language (don’t get me started on using “reticent” to mean “reluctant”), but my main objection does stem from using what was once an adjective as a noun. Calling a person a “creative” does not just describe the occupation, like “actor”, “engineer” and “financial analyst”. It ascribes a character and talent to the person.

What’s wrong with that? Well, first of all, it’s a broad brush. Members of the ad industry are routinely called “creatives”, but how many of them really are? (and if you’re going down that road, might as well call political campaigners “creatives”). I’m not just picking on ad people. Realistically, any occupation is going to have plenty of people who just aren’t that good at their jobs, or at least not good enough to be considered gifted at it.

And frankly, it’s elitist. Calling someone a “creative” implies that anyone who isn’t one, isn’t. Creative, that is. It’s like calling someone an “intellectual”, as a noun instead of an adjective. Oh, right, we do that. But you have to admit, it’s kind of snooty (tune in for Wil Wheaton’s Conversations with Intellectuals…snore), especially when you use it on yourself. Like when LinkedIn profiles have “visionary” in the description — again, noun instead of adjective.

But for that reason, “creative” is probably here to stay. Calling yourself a “creative” is like wearing a cool jacket (the same jacket that Don Draper wears)— as long as it’s in style, you can get away with it, and there’s probably some self-affirmation value in it (I’ve seen quite a few meetups for “creatives” to get together, and even “young creatives” — there’s a nice puppy, good puppy!)

Alas, with all these adjectives turned nouns, I’ll have to update my LinkedIn profile from “creative, intellectual visionary” to the more verbose “a creative, an intellectual, and a visionary”. And a “humble”, as soon as that turns into a noun.
