= Kim’s Convenience

(missing videos)

When I tell people I like to watch Korean dramas, they typically ask “Oh, are you Korean?” No, I just get tired of watching American shows with no Asian faces (I don’t actually say that).

But recently I binged Kim’s Convenience, which is not a Korean drama, bur instead a Canadian sitcom. It’s my favorite show with an Asian-American cast (out of the three I’ve seen in the last thirty years). And by Asian-American, I’m including Asian-Canadian, as this show is based in Toronto (yet another reason to move to Canada these days).

The dialogue is sharp and witty, there is emotional depth, and all of the actors do a great job (it feels good just to see Asian-American actors get work), and I’ve watched enough Korean drama to recognize all five of the Korean words uttered in the show. And in fact there is even a visiting cousin straight out of a typical kdrama making a couple of appearances.

It’s not all about the Asian immigrant experience. It’s a show with a variety of characters with different backgrounds in everyday situations.

But the heart of the show is Mr. Kim and his relationship with his family.

My favorite relationship in the show is between Mr. Kim and Mrs. Kim. And my favorite scene is her singing Love Shack.
