= Have Expectations

I once had a salary review in which my boss explained there’s always something you can do better, so she always made a point to bring up that something in the review. In this case, she said she’d like me to volunteer for tasks more often, whereupon I replied that every time I did that, it turned out badly. To that, she responded, “I don’t know what to say to that.”

Nevertheless, I think she had a point, but one problem I’ve seen in workplaces is there’s always someone who people don’t expect to improve. For example, in that same workplace, there was a guy working with a PhD working on the algorithmic side, and more than one person told me he had to be supplied with prebuilt libraries of our code. I don’t know if they just assumed he couldn’t perform the necessary Visual Studio build steps or if he’d made a fuss about it, but when I went through it with him, he had no problems with it, and it seemed to me he was happy to have that much more control.

It is a bigger problem if the person really doesn’t want to learn. That’s how you eventually end up like my coworker who pretended to make progress for months and later was passed around from group to group as a charity case.

Sometimes this happens because of the social dynamic. People who don’t know anything about what you do are non-threatening because they don’t know anything about what you do. You can see this in the typical programmer-marketing dynamic. While programmers always complain how marketing doesn’t know anything about the tech, while not really expecting them to know it or making much of an attempt to explain it, and meanwhile marketers get impatient at long explanations and complain “I just want a yes or no answer!” (you can substitute management for marketing).

It’s more insidious when this happens between management and employees. I’ve been at more than one place where the top dog enjoyed complaining about their incompetent underlings but never really expected them to do a better job, and those mediocre workers ended up as the longer-lasting employees. Which just goes to prove that your job is to make the boss happy, and sometimes that means making him feel superior.

Of course, despite the stories about people getting thrown into the deep end and flourishing, you can’t always expect dramatic leaps in capability and production. That’s sometimes what happens to those pigeonholed as hopeless — they fail and flail and then no one (including themselves) expect further success. But like my boss said, you can always improve. Start small if you have to, but get better.
