= Apologize

I never see this on what-do-employees-want-from-their-workplace surveys, but aside from stock options and free lunch, I think employees really appreciate a good apology. Or maybe they just don’t realize what they’re missing. I’ve received few enough that I remember them vividly.

The first management apology I received was at my first job, where I received a tepid first salary review (I think the word “disappointed” was used), but later my boss said he made a wrong assessment. Admittedly, this was when he was trying to keep me from quitting. But I felt he was sincere.

And it’s hard to give a good apology without being sincere. Insincere apologies tend to be about things beyond their control (“I’m sorry the business climate has been so tough” instead of “Sorry we didn’t pay you”) or even criticisms of others, like the group confessional we also had at my first job (a mother-lode of Dilbert source material), when we went around in a circle and “confessed” what we could do better, which was usually what we could have helped that other guy do better. I hear they also do this in North Korea.

The same goes for the apology’s junior partner, the admitted mistake. “I made a mistake by hiring the wrong people,” for example, is an efficient way to pass the buck, to everyone else. On the other hand, hearing, “Yeah, that was a bad idea,” gives me not just a feeling of vindication but also some hope that it won’t happen again. It can also get people off your back, like when one of my bosses said, “Alright, alright, I made a mistake, stop bringing it up.” I was gratified, but I really wasn’t trying to nag — when you’re recounting history, you don’t omit unpleasant parts (except in certain school textbooks).

Some people are famous for never apologizing or admitting a mistake (and some professions discourage it), but it doesn’t have to be a big deal. Throw in a simple “You’re right” here and there, and work your way up. As with many things, admitting to mistakes or apologizing sooner and more frequently avoids bigger confessions later.

But as they say, apologies are better late than never. One former manager apologized to me and a coworker a few years later for not being a particularly good boss. He was looking for a job at the time, but it was nice to hear.

Nevertheless, I don’t really take apologies to indicate a change. One client apologized to me for being disrespectful the previous day in snapping “I don’t care, I just want it!”, and that’s a grade A apology — you rarely see an apology for behavior and using the word “disprectful”. But it’s not like he never threw a tantrum again. I just appreciate apologies in the same way as those employee achievement awards that don’t have any monetary value but look good on your LinkedIn profile. Actually, those LinkedIn recommendations would carry more weight if they were in the form of apologies, e.g. “We should have paid him more.” or “Our mistake for not promoting him.” You get the idea.
