= The Chocolate Factory
technicat
technicat
Dec 5, 2016 · 2 min read

As a child, I enjoyed reading Roald Dahl’s Charlie and the Chocolate Factory (although my favorite was James and the Giant Peach). But if memory serves, I didn’t finish watching the movie (the old Gene Wilder version) in the theater because I got freaked out by the scene with the Oompa Loompas singing the creepy Oompa Loompa song and rolling around the girl who inflated into a giant blueberry.

Honestly, that scene still freaks me out, but it apparently didn’t bother my nephews when we saw the movie on TV, recently, so I finally finished it.
Image for post
Image for post

I was surprised how the movie has stood the test of time, thoroughly enjoyed by my nephews, and I liked Gene Wilder’s sardonic performance.

And coincidentally, not long after I returned home, I found there’s a real chocolate factory a short walk from my apartment, with a shop from which you can view the chocolate production. I don’t know if it’s another coincidence, but those blue hardhats remind me of the Oompa Loompas.
Image for post
Image for post

Now, the factory doesn’t have a glass elevator that goes into outer space (I would like to see a movie based on that book sequel), but for some reason it does have a three-acre cactus garden, so you can sit and enjoy a coffee and chocolate from the factory store.
Image for post
Image for post

And there’s more! During the holiday season, the cacti are decked out with holiday lights.
Image for post
Image for post

I think Gene Wilder would have liked it.
