:toc:

= Blame Canada


Another one (actually a couple) from the archives several years ago. You might think I dug these up based on the current administration’s campaign against non-white foreigners and immigrants, but really they came back to my mind in the pre-Trump days when I saw Bernie Sanders exhort the audience in his debate vs. Hillary Clinton that they shouldn’t have to compete against low-paid Mexican and Vietnamese workers. Some things don’t change.

Amid all the television news stories on the economic crisis, I saw a report detailing the woes of Canadian carmakers, namely GM Canada, Ford Canada…apparently there are lower employee costs in a country that doesn’t rely on employer-sponsored healthcare. Aside from the competitive disadvantage imposed by the US healthcare system, another thought occurred to me — I’ve never heard anyone blame Canada for taking our jobs.

I remember way back in the 80s when Gephardt was campaigning for the presidency and talking up the Japanese scare with auto unions, but I’ve never heard a peep about US auto jobs moving to Canada. Ross Perot warned of that sucking sound of jobs going south, not north. I’ve heard Lou Dobbs warn about terrorists, disease, criminals and job-stealers crossing the Mexican border but nothing about Canada (to be fair, I don’t watch angry white man shows much, so maybe I missed something). When EA shut down it’s Seattle office and opened up a new one in Vancouver, the only controversy there was the EA Spouse story, but game outsourcing to China is worth a Game Developer Magazine issue. When a highly automated Mac factory was constructed in Ireland, the story was about how cutting-edge and automated that factory was, while stories about iPod manufacturing in China are about outsourcing to China (OK that’s Ireland, not Canada, but somehow Blame Ireland isn’t such a catchy blog title).

While aerospace jobs here in Huntington Beach moved to Arizona and a good portion of your favorite TV shows and movies are filmed not in Hollywood but in Canada (where they have rules requiring the hiring of Canadian actors, as I learned on the commentary of Slither), the Orange County IT and programming mail lists I subscribed to were filled with whining about Indian programmers taking our jobs. One poster somehow ended with a lament that Mexicans were hard-working and friendly but didn’t value education. I could have rejoindered that’s what I thought about white people, but actually, a disproportionate number of my programming coworkers have been white people — Europeans and, you guessed it, Canadians.

I know there are a lot of protests and counter-arguments that can be made, and I’ve heard them all from the aforementioned mail lists, ranging from I’m not a racist to trends…yada yada…magnitude…yada yada…but all I ask is, if you’re hand-wringing about the Chinese and Indians and Mexicans, be fair and just once in a while, blame Canada.

And another one in similar vein:

Below is a list from Wikipedia of scifi TV shows filmed in Canada since 2010. That’s just since 2010, and just sci-fi shows. Imagine the list since 2000, for example (also in the same wikipedia page if you’re curious) and expand it to all genres. And think about movies. The reason I bring this up is that when people complain about jobs going to other countries, it’s always Mexico or an Asian country. I hear this from white Californians, Fox TV (and CNN until Lou Dobbs left) and campaigns from both parties during election season (“Bangalore!” and “Beijing!” featured prominently in Meg Whitman’s campaign, and the Obama campaign is uttering “Mexico!” and “China!” against Romney — it’s nice to see such bipartisanship). I have yet to hear a complaint about film production and acting jobs going to “Hollywood North”, or any other type of jobs (there is a Canadian auto industry, and check out all the hi-tech offices EA, IBM and Microsoft opened there). But I suspect if filming moved down to Mexico (or Bollywood), you’ll start hearing about it.

    Alcatraz (2012)
    Arrow (2012)
    Continuum (2012)
    Covert Affairs (2010)
    Haven (2010)
    Human Target (2010)
    Les Rescapés (2010)
    Lost Girl (2010)
    Once Upon a Time (TV series) (2011)
    R.L. Stine’s The Haunting Hour (2010)
    Tower Prep (2010)
