= East Meets West

Recently, I read a magazine review of a Korean coffee shop here titled “East Meets West.” That phrase just makes me want to set the magazine on fire. For one thing, it’s incredibly overused.


It’s like the default title for anything remotely involving anything Asian, such as the Chinese art exhibit at my local public library, or Margaret Cho’s show eventually named All-American Girl (another title they dodged was “Wok on the Wild Side” — if there’s anything worse than East Meets West it’s another wok pun). By the way, I hope we don’t have to wait another twenty years for a show featuring an Asian-American family.

Besides being lazy and annoying, it’s insidious. What would you title a review of a French cafe? “West Meets West?” A Mexican restaurant? “South Meets West?” A Tim Horton’s? “North Meets West?”

It’s the type of exoticising of all things Asian that leads to the Japanese-American internment and people asking me “Where are you from? No, I mean where are you really from?” Asian-Americans have been here in quantity for over two hundred years (and there would be more of us if not for immigration and naturalization restrictions). East Meets West is a fine description of Marco Polo’s adventures, but nowadays, we’ve already met.
