= Where are you on the Racist-O-Meter?

The problem with calling someone a racist is no one believes they’re racist, even though we evolved as biological generalization-making and snap judgement machines (see Malcolm Gladwell’s books), and have been fed with biases and stereotypes by society and culture (even bots get racist when exposed to the Internet).

Yet Silicon Valley tech execs who pride themselves on rationality are unable to believe themselves capable of even subconscious bias, even as they sell advertising space and distribute fake news. So what can you expect from those who consume it?

If we all admitted we’re at least a little bit racist, then we can move on to how racist are you? Like at the Japanese curry restaurant I frequent, where they ask how spicy you want it on a scale of 1–20 (3 is a medium, which probably works for racism, too).

If you voted for Trump because you like the racist things he said, then you’re high on the racist-o-meter. I mean, you voted for the same reasons as David Duke. If you voted for Trump despite the racist things he said, then you’re probably still at least in the mid-range, because those racist things apparently just aren’t that important to you. Whereas, say, if you’re Muslim, then being banned, listed in a registry, or worst case, ending up in a concentration camp, is a deal-breaker.

Now, I did see a Medium blog titled something like “I’m a Muslim who voted for Trump and I’m not racist” from a woman who voted for Trump because she didn’t believe he would be allowed to keep his racist and anti-Muslim promises. In this particular case, I believe her, she’s not a racist. She’s an idiot (and the problem with calling someone an idiot is no one believes they’re an idiot). That’s just really bad risk management.

That reminds me of this one storeowner who told me Trump was the guy to get us out of this mess, because the qualified people got us into this, so it will take an unqualified guy like Trump to get us out…unless he turns into Hitler. Again, bad risk management, and if he wasn’t white, I expect he’d take the Hitler thing a bit more seriously.

But actually, among the storeowners (for some reason they were mostly storeowners) who tried to convert me to Trump this summer, he was the only one who was white, and he was the only one who wasn’t blaming the country’s ills on illegal aliens, so it goes to show minorities can be as racist as anyone else, especially if it’s against another minority. I’ve discovered this also on plane trips (I’ve got to stop flying Grievance Coach class), having sat next to a Muslim couple complaining about Jews, and an Indian woman complaining about Muslims. If they would just all get on the same flight together…(story idea!)

On the other hand, if you have a mixed heritage, that cuts down the number of groups you might feel prejudiced toward. I’m Chinese-American (usually I just think of myself as American, but people keep reminding me I’m Chinese), with white, other Asian, Muslim, Jewish, Christian, very Christian, agnostic, atheist, probably some Buddhist, and gay relatives.

As a consequence, I’m easily offended. For example, while I was living in a New Jersey town that looked like it’d been a target of Chris Christie retribution, a woman told me, “I don’t care about the color of anyone’s skin,” which invariably leads to a racial monologue, which in this case included the tidbit that “you know, Obama is from the ‘neighborhood’”, and “he’s Muslim because his father was Muslim and they say that makes him Muslim.” When I pointed out that that would make me Muslim (not that there’s anything wrong with that), she said “but you’re not a terrorist, right?”

So apparently, while being related to a minority (or if you’re a minority, a different minority) may broaden your perspective, just talking to one, not so much, notwithstanding one Medium blogger’s contention that we should do business with Peter Thiel in order to engage with Middle America (I can’t imagine a German-born Bay Area billionaire has much relationship with Middle America beyond flying over it a lot).

Which is another example of how this election has brought out the stupid in a lot of blogs. But while we’re waxing (blogging) ridiculous, I recall another story idea I had about a society where everyone could only marry someone of a different race. I don’t know if it would make a good scifi novel, but it would be a fun campaign platform.
