= Sci-Fi Stereotypes

The new Heroes series, Heroes Reborn, looks mildly intriguing, but I didn’t watch all of the original, losing enough interest during the second season to pause and complain about the first:

I was absorbed by Heroes in its first season, but after a disappointing second season and with the third not looking any better, I can start harping on the lack of imagination (ironic for this series) in ethnic portrayals. The variety is far better than most of television, especially the lily-white WB (I’m looking at you, Gossip Girl!), but all the Asians are from Japan (and the two principal ones are nerdy salarymen), and of the black characters, one was Haitian, the other a convict, and his relations (introduced in Season Two) lived in the ‘hood. Season Two introduced two Latinos, both illegal Mexican immigrants. I was astonished to see an African-American “hero” at the beginning of the most recent episode, but she lasted about two seconds before Sylar ate her brain.

Of course, this is nothing new. My favorite sci-fi show of all time is Firefly, but nowhere is it explained why everyone speaks Chinese slang (badly) yet there’s no Asian in sight. And while Star Trek was progressive for its time (the first one, anyway), in the future Federation there appears to be a lot more interspecies dating than interracial dating. As a result, you don’t see anyone on the Enterprise with an obviously mixed ancestry. Not too many accents (except for Scotty, and poor Chekov), but characters’ ethnicities are identified heavily by their names. Jean-Luc Picard is so French that in a time-hopping series finale he’s seen retired on a French vineyard.

A more insidious problem with Star Trek is the foisting of convenient ethnic cliches on poor aliens — the brutish dark-skinned Klingons always looking for a fight (although the TNG version acted more like Vikings), the inscrutable Oriental-looking Vulcans and their cousins, the devious, calculating Romulans.

You can’t just blame the original series — the newer series introduced the Ferengi. small, stooped, money-grubbers with big…ears (making them erogenous zones was a nice, er, touch). And the Borg — why are all futuristic alien hive minds so unfriendly and dull? (In other words, why not Mac, rather than Windows? There should be a Borg on the Microsoft commercial, saying “I am a PC”)

Sci-fi shows should be the first to turn around conventions, especially if you get to play with aliens. There’s no reason Ferengi couldn’t be a tall, athletic species (hey, look at all the professional athletes who love to gamble with all their professional endorsement money), Klingons and Cardassians could look like swimsuit models (after all they did that with one Borg), the regal Vulcans could be short, hairy and fat. And those tribbles would be a lot more interesting if they were aggressive and carnivorous, or looked like sea slugs. Now that’s a show I’d like to see.
