= I Can’t Take Off This Shirt

I’ve learned not to wear red shirts at Target, as inevitably a customer will assume I work there. And also, I’m out of red shirts (maybe reading John Scalzi’s book has something to do with it).

I’ve had a similar problem at Asian restaurants. Not so much on the west coast, although there was an Asian bistro (whatever that is) where as I exited someone passing asked me if I was still open. But that’s a rarity.

The east coast is a different story. Particularly in New Jersey (adding to my list of reasons why I don’t like going to New Jersey), where, for example, one customer complimented me on my beautiful baby (the restaurant owner’s baby), and other customers kept telling me the order they were there to pick up.

It’s not like I was sitting behind the cash register. In each case I was sitting at a dining table or waiting area. You know, where customers go.

It would be easier if Asian restaurants all had uniforms. Then I could just avoid wearing a certain shirt. Maybe that would work. Maybe.
