= Books of 2019


Prompted by Barack Obama’s top books of 2019, I took a snapshot of my goodreads list, dating back about half a year (my goal has been to average a book a week, which I’m pretty close to with the help of comic books).

I recommend all of these books except Building Software Teams, which is the type of book you might expect from a software process consultancy (you can learn some terminology from it, but it’s not a substitute for in-the-trenches advice).

My highest-rated books aren’t necessarily the ones I most recommend. I found the writing in Boom Town entertaining but for that reason suspect — how much is exaggerated? But there’s important history in there, including the Tulsa massacre now made better known by the Watchmen series.

Similarly, I thought Code Girls spent too much time on the dating lives and engagement plans of the women coders and could have spent more time on the racial discrimination issues and the women’s contributions after WWII, but nevertheless the book reveals history that everyone should know (I found it ironic that women were recruited as code-breakers on the belief that they were more reliable than supposedly more creative but neurotically temperamental men, which is pretty much the opposite of the Google Manifesto).

The Narrow Corridor was a slog, and I had to renew it several times (my library card contributes any eclectic quality to this selection — I generally grab any interesting-looking book in the New Releases section because I like to read shiny smudgeless books). I’m not convinced all the historical case studies are easily wedged into their political theory, but again it’s a lot of important history about the rise and fall of governments since ancient times, with all the attendant wars and oppression and atrocities. So it’s a bit depressing, even if the authors are cautiously optimistic about the current state of affairs.

On a lighter note, the dim sum and tea reading is for my dim sum app, but I’m amazed how many people I’ve met have never had dim sum, even here in Las Vegas with nearly a dozen dim sum restaurants. Someone even asked me recently if there’s a difference between Chinese and Japanese food! And honestly I hardly knew the first thing about tea, which is at least as interesting and varied as coffee.

The science fiction books are courtesy of my local neighborhood indie bookstore, except the latest Expanse book which I ordered from bn.com during a sale day. I did a refresh of The Handmaid’s Tale before reading the sequel Testaments (and finally watching the series), and broadening my horizons with Le Guin, Liu, and Liu (sounds like the scifi version of a law firm).

Specific books aside, I also recommend make use of your local library, support your local bookstore, and if you order online, go to bn.com instead of amazon, because they have mostly free shipping on books, and they’re not amazon.
