= Carl Melcher Goes to Vietnam

Last week, I checked out the local Dave and Buster’s (it’s a happening place on Friday night, like Chuck E Cheese with a bar), and I was reminded of the Epinions meet ‘n greet they held at the Irvine Spectrum Dave and Buster’s oh so long ago, when Epinions was cool and before they were bought by shopping.com (which was later bought by eBay).

Along with BBQ wings, some books were handed out at that shindig, including Paul Clayton’s self-published https://bookshop.org/books/carl-melcher-goes-to-vietnam/9781468130997[Carl Melcher Goes to Vietnam] (I heard he got a publishing deal, but I haven’t seen any other edition of the book). In truth, I made a few abortive attempts at starting the book, but the first-person narrative by young draftee Carl Melcher begins slowly — the tone of the first chapter describing Carl’s transport to Vietnam for his tour of duty seems sterile and his travelling companions uninteresting and somewhat unlikable.

In the context of the whole book, I think it works. The autobiographical feel of the book is strengthened by the understated narrative. Carl is not a poet or activist or John Wayne. Carl is the Everyman soldier who’s in Vietnam because he doesn’t feel he has a choice. Yet when he arrives, the experience is almost a disappointment. It’s almost like a trip to summer camp, bunking for a few months with some new buddies, and despite the helicopters and bombing runs and mortar fire and wounded and dead, contact with the enemy is so infrequent that Carl develops a half-serious theory that the whole thing is an elaborate hoax.

There are casualties among Carl’s friends, much of it self-inflicted by “Keystone Cops” bungling, but Carl’s fatalistic go-with-the-flow attitude seems to be working — he even falls for a local girl (and I mean girl — she’s just a teenager, which seems a bit shocking until you realize so is Carl) and plans on prolonging his stay in Vietnam to be with her. There’s even a bit of Catch-22 bureaucratic fumbling with his personnel file, so it seems like there might be a happy ending in store for Carl.

But this is not a story, it’s real life and real war, and in particular it’s the Vietnam War where politicians posture at peace talks while soldiers try to survive their tours of duty despite themselves, an unpredictably hostile populace and an often faceless enemy. Carl survives, but his friends don’t. He returns home as if awakening from a bad dream, but as the book leaves off, it seems it’s not a dream that he can shake.

This may seem like a pointless ending to the story, but that’s the point. _Carl Melcher Goes to Vietnam_ may lack the morality implications of Platoon, the existentialism of Apocalypse Now or the detailed battle intensity of We Were Soldiers, but it feels real enough that I’d like to know how much of it stems from the author’s experience.
