= Cellphone: The Story of the World’s Most Mobile Medium and How It Has Transformed Everything!

Reading _Cellphone: The Story of the World’s Most Mobile Medium and How It Has Transformed Everything!_ is like being on the receiving end of the most maddening and pointless conversation you’ve ever had:

I-have-the-last-word-in-the-argument:: In the preface, the author states that he won’t discuss the debate about cell phones causing brain tumors, then immediately adds, “The claims are unsupported by medical evidence.” That’s like my previous boss who would say something rude, followed by “let’s not discuss this anymore,” then toss in a final insult. Anyway, even if I were to trust a professor of media studies to assess medical data, a book ostensibly about the cell phone’s impact on society should at least describe the not insignificant concern about cell phone radiation.

the provocative and ridiculous assertion:: The author claims the cellphone has had a bigger impact on the world than the Internet. Yet he devotes much of the book to the advances of the Internet. (In fact, much of the book is devoted to the history of telecommunications starting with the telegraph and to non-unique aspects of the cell phone, like the Pavlovian response to phones ringing) He asserts that the videophone coverage in the Iraq war was completely objective, with Geraldo Rivera’s disclosure of his unit’s location as an extreme example of objectivity, while the one exception was Dr. Sanjay Gupta, who interrupted his broadcasting to administer emergency medical treament to a two-year old Iraqi boy. (The author says Dr. Gupta’s objectivity was questioned, but doesn’t say by who). What about Rivera’s relentless self-promotion — that counts as objectivity? Perhaps it’s time for Geraldo to start a new talk show using videophones, that would really add some objectivity.

dumb analogies:: The author cites cites Stephen Jay Gould’s explanation of “preadaptation”, how evolutionary products such as walking limbs later can transform into other functions such as wings, then proposes that thumb-operated cell phone buttons also qualify. That’s ridiculous — cell phones are designed (or mis-designed) for our digits, not the reverse. It’s called user-interface design or human factors engineering, but definitely not evolutionary preadapation, unless our thumbs have started changing shape to match cell phone buttons.

facts out of context:: The early laptops, circa 1983, are described as limited by their operating system incompatibility with CP/M, DOS and the Macintosh. Well, those three operating systems were incompatible with each other, and there were plenty more at that time — just about every line of computers had its own OS. (even within Apple, there were the mutually incompatible Apple II, Apple III, Lisa and Mac OS’s.)

rambling:: the book is 256 pages, with surprisingly little dedicated to cell phones, but snippets of just about everything media in the twentieth century. Like postcards?

shameless self-promotion:: The book is filled with “See my book…”, and the bibiliography section at the end of the book lists thirteen works by the author.

annoying coined phrases:: The author describes anything cell phone related as “cellphonic”. From now on, I’ll call everything about books “bookolic”.

_Cellphone_ reminds me of my stoned friends pontificating aimlessly and circuitously over technology, society and philosophy. (At least I hope they were stoned — broadcasting several minutes of such interminable discourse would be a more powerful anti-drug message than a two-second display of sizzling fried eggs). I’ve often grumbled about how today’s cellphone culture contributes to short attention spans and disconnected thought — it never occurred to me that a book about cellphone culture could be the worst example.
