= Console Wars

The most entertaining part of Blake J. Harris’s https://en.wikipedia.org/wiki/Console_Wars_(book)[Console Wars] is the forward by Seth Rogen and Evan Goldberg. That isn’t a knock on the book — the forward is just really entertaining banter. The rest of the book is entertaining, too, and it should be, considering the subject matter: the video game industry, in particular the head-to-head battle between Nintendo and Sega during the SNES and Genesis years.

However, the story feels incomplete, as it ends with Tom Kalinske’s departure as the head of Sega of America (and it begins with his hiring there, so the book could have been more boringly but precisely titled Tom Kalinske’s Time at Sega), so it doesn’t cover anything after the Sega Genesis, including their last console hurrah the Dreamcast (the one Sega machine I owned), or what they’re doing now (I have some curiosity on the subject as I worked for a game studio several years ago that was acquired by Sega).

And the book reads like a made-for-movie or made-for-TV script, with dialogue that sometimes feels contrived (there is a disclaimer in the beginning that the conversations are reconstructed) and so over-the-top prose. There is also the tendency, common among male writers of tech books and pulp thrillers, to describe women in terms of physical attractiveness and men in Norse god ranking, e.g. women are “brunette” and “doe-eyed”, while men are “steely-eyed” and hair is not mentioned except when it’s absent. But if you’re at all interested in the video game industry, this is an informative and engaging read.
