= Finding Serenity

I was sure I’d read https://en.wikipedia.org/wiki/Finding_Serenity[Finding Serenity:Anti-heroes, Lost Shepherds and Space Hookers in Joss Whedon's Firefly], a collection of essays on the TV show Firefly edited by Jane Espenson, but there it was on the sale-priced-because-the-show’s-closing pile in the waning hour of this year’s Comic Con, and skimming it, I didn’t recognize the articles, so I bought it. Good deal, turns out the book I read previously was https://firefly.fandom.com/wiki/Serenity_Found[Serenity Found], the sequel.

After those two Firefly books, and some Buffy and Angel collections, I’m beginning to recognize a pattern. Books on the Whedonverse are mostly stuffed with analyses from adoring fans, one or two reminisces from the cast and crew, and for some reason there’s always one really annoying essay (like the Buffy essay complaining the show isn’t that humorous — it could have been condense to one line: “I don’t get it.”). And in the case of Firefly, a healthy dose of Fox-bashing.

The cast contibution in Finding Serenity is provided by Jewel Staite and is so cheerful and sweet it could have been written by here character Kaylee. The token obnoxious essay is by a self-professed fan who feels the show is missing the chivalry of the Old West, going on and on about “modern sensibilities” and even referring to his wife as an “authoress” — I get it, when men were men and women were women and I think you’re confusing chivalry with chauvenism and who let Archie Bunker write a Firefly essay?

The essay that prompted me to buy the book is one that I felt was missing when I read the sequel first, titled Asian Objects in Space and pointing out the lack of Asian representation, or at least an explanation of that lack, in this Chinese-speaking (mangled-Chinese speaking) ‘verse. It doesn’t exactly take Joss Whedon to task (this is a fan essay collection, after all), but rather speculates some event in the ‘verse history that has yet to be revealed.

But a simpler explanation is oversight. The essay Chinese Words in the ‘Verse notes the dialog was originally supposed to be Cantonese, but the translators just assumed it was Mandarin (or maybe they only knew Mandarin?) It’s a mixed bag — I’m surprised and delighted that Whedon actually knows there’s more than one Chinese dialect (or language, depending how you view the differences) and dismayed at the follow through. I mean, it’s not hard to find a Cantonese speaker in Los Angeles (just go to a dim sum restaurant). In fact, one voice actor (who probably only knew Cantonese) spoke her lines in Cantonese.

I have a couple of apps on the App Store that feature Cantonese text-to-speech (Apple has Cantonese built into Macs and iOS devices, great for the Hong Kong market). The chapter listing all of the Chinese dialog in Firefly gives me an idea for another one — an app that pronounces Firefly Chinese as it was meant to be heard: in Cantonese and not horribly mangled. I’m serious. Stay tuned.

Firefly is still one of my favorite shows and maybe the favorite, but not because of the ain’t-it-cool Chinese trappings. In that respect, I feel it’s all hat and no cattle. But I’m impressed that _Finding Serenity_ has three chapters devoted to it, so that’s something.
