= Haunted Empire

https://www.harpercollins.com/products/haunted-empire-yukari-iwatani-kane?variant=32207578234914[Haunted Empire: Apple After Steve Jobs] directs a much-needed focus on the negative aspects of Apple’s impact on the world, particularly the pressures brought to bear on Asian manufacturers, and juicily brings to light the discordant elements of Apple’s internal politics.

But it seems too grimly determined to cast a dour look on Apple, I think unfairly characterizing the current management’s capabilities out of hand and dismissing the company’s chances.

Basically, it’s just too melodramatic, as evidenced by the chapter recounting the forlorn Foxconn life of a young woman in China — I spent most of the chapter expecting it to end in her suicide, coming as it did after the chapter listing Foxconn suicides, and thankfully it didn’t, but really, it was an unnecessary detour (it could just as well have been a separate book, fiction or non-fiction) and as much an indictment of China and Chinese culture as Apple. Still, it provides a welcome alternative to the worshipful treatments of Apple and Jobs.
