= The Hunger Games

I read the https://en.wikipedia.org/wiki/The_Hunger_Games[The Hunger Games] almost accidentally — it happened to be at the top of the list of Kindle books I could borrow while trying out Amazon Prime, and I remember seeing an entertainment news personality excitedly discussing the upcoming movie, so I figured why not.

And one bleary-eyed all-nighter later, I’d finished it. The action is compelling, the vision of this dystopian future is fascinating, and the concept of the Hunger Games — kids fighting to the death in a combination of gladiatorial and MacGyver combat — is original and twisted.

So I was pretty surprised later to hear that this is a “teen” novel (but I’m glad to see some teens are reading this instead of Twilight — after two pages of that I thought my brain would explode, just like when two teenage girls sat near me at the local pizza parlor and talked about boys and texting for half an hour. Substitute vampires for texting). I suppose I should have been tipped off by the oh-no-two-boys-love-me-what-shall-I-do handwringing, which was getting on getting on my nerves, but I do like the Katniss’s attitude of I-don’t-have-time-for-this-I’m-on-a-mission. Literally, she’s trying to be the breadwinner. Now that’s a modern (or really, postmodern) woman.

And I’ll admit it, I was getting into the romantic aspects, to the point where I was wondering about the chasteness of the whole book (another tip that it’s targeted to the teen demographic). But I’m not embarrassed to be a fan of this story. I’m really not. Especially after I just read in the sporting news that LeBron James has been reading Mockingjay (the third in this trilogy) in the locker room before each game of the Heat-Celtics series, including his 45-point high-percentage Game Six. I wonder when he was raining down all those shots if he felt like Katniss letting fly an arrow.
