= A Story of Reality Distortion

Despite my not being a Steve Jobs fan, or perhaps partly because of it, I found Walter Isaacson’s https://en.wikipedia.org/wiki/Steve_Jobs_(book)[bio of Jobs] absorbing. On aggregate, it didn’t tell me anything new (Jobs personality, failures and successes are pretty well documented), but it comprehensively filled in a lot of detail, especially from his childhood to his early adult years, and the depiction of his illness is wrenching.

As a business study, it is illuminating, covering not just Apple, but Pixar, all the way to its merger with Disney, NeXT, and competing players like Microsoft and Google, although the history lacks some technical insight. For example, it was clear to me and I’m sure others at the time that both Microsoft and Apple had to get over the OS hump (one of my Bay Area commented, core competency-wise, there are some companies that do OSs and Apple wasn’t one of them) from their early PC days; Microsoft ended bringing in people from DEC to get them Windows NT while Sculley unfortunately depended on a partnership with IBM. I always felt he was unfairly maligned (my favorite Macs were from the Sculley era), and he gets the same treatment here (but not as much as Amelio).

Although this book is about Jobs, I find the supporting cast just as interesting, especially his biological sister and his belatedly acknowledged daughter, but also his lieutenants and partners — Ives, Cook, Cue, Forstall….and of course Wozniak (let’s not forget him), who is perhaps as perfect a counterpoint to Jobs as could be conceived even in fiction.

In the end, what I find fascinating is not Job’s reality distortion field and his self-assurance that rules applying to everyone else didn’t apply to him, but how people reacted and still react to that. And I’m left with the perhaps the mundane question I can’t shake: how can someone who spent his while life refusing to put license plates on his car and parking in handicapped parking spots still be allowed to drive? I guess the rules really didn’t apply to him.
