:toc:

= Rethinking Narcissism

We’ve all had selfish colleagues, and I even worked with a pathological liar (he was in marketing, so it could have been worse), but a full-blown narcissist is something else. I was really taken aback by my first completely self-absorbed boss (a lot of them become bosses) who’s mantra alternated between “Look at it from my point of view” and “No one knows how hard it is for me” while telling everyone to work overtime as she went off to aerobics class.

She especially felt sorry for herself when firing someone. These conversations make her really uncomfortable, she explained to me while simultaneously not paying me (when I asked if she wanted me to continue my contract, she apparently assumed I meant without pay) and complaining she felt I was taking advantage of her. You’ve never really been exploited until you’ve been exploited by a narcissist.

I say “first boss” because I worked for a second one, a Steve Jobs wannabe (one sign of a narcissist is they admire famous narcissists — not so much for the accomplishments as for narcissistic with impunity). It surprised me that there could be two such similar people, but at least this time I was prepared and got out of Dodge when he transitioned from the effusive you-guys-are-awesome honeymoon period to the peevish I-don’t-see-why-I-should-pay-you rumblings.

Craig Malkin’s explanation of narcissism in http://www.drcraigmalkin.com/the-book[Rethinking Narcissism: The Bad-and Surprising Good-About Feeling] would have helped my narcissist-recognition skills. It describes and confirms what I already thought about these extreme cases: these level 9–10 point cases on a 10-point narcissism scale are too far gone for you to do anything about (like alcoholics, they have to recognize the problem themselves)— avoidance and damage control (if avoidance is not an option) are the best you can do.

He describes some narcissistic patients and patients who have narcissists in their lives, but I do wonder how much the patients who complain can be trusted in their narratives. How do we know they’re not the narcissists? (What I’ve learned is that narcissists can spin a good yarn — they make the best conspiracy theorists). And of the narcissists he treats, how does he treat them? While he suggests interventions and appeals to empathy, the book is depressingly barren of cured-narcissist case studies.

But the main thrust of the book is that there is a healthy level of narcissism, and in fact there is dysfunction in not having enough (“echoists”), evident in people who are uncomfortable receiving compliments, for example. You can imagine an echoist-narcissist pairing is a bad combination.

Of course, this is all on a spectrum, the aforementioned 1–10 scale, and the book includes a narcissism test (in case you’re wondering, the scoring does compensate for narcissists biasing their answers toward non-narcissism), and suspicious of pop psychology texts as I am (Narcissists are from Mars…), I appreciate the described history and differences in opinion on the subject (narcissism is bad vs. narcissism is not all bad).
