= The Second Life Herald: The Virtual Tabloid That Witnessed the Dawn of the Metaverse

https://mitpress.mit.edu/books/second-life-herald[The Second Life Herald: The Virtual Tabloid That Witnessed the Dawn of the Metaverse] by Peter Ludlow and Mark Wallace brings up many interesting issues including avatar rights, how or whether to report possible real-world crimes that are related in the virtual world, corporate undergovernance and overgovernance, online misbehavior, underage users operating virtual prostitutes….

But it’s obscured by the usual fascination with cybersex (teledildonics, anyone?), the grudge-like complaining over how Ludlow was treated by EA during the Herald’s Sims Online years (it sounds like me complaining about my cable provider) and the distracting use of third-person in a first-person narrative (it’s mostly about Ludlow). Imagine listening to a sports star (or star journalist?) talk about himself in the third person at book length.

The Herald itself is entertaining, though not updated in a couple of years, and the About page gives you a taste of the tone of the book. One thing I’ve learned from working with virtual worlds (including participation in a developer meeting in-world for Blue Mars), is that putting something in a virtual world makes it more interesting.
