= Ultimate Punishment

The death penalty, like abortion, is one of those issues that seems to inspire strong opinions in just about everyone, regardless of personal experience or knowledge. Like most people, I consider myself a moderate — I have been uncertain about the morality of capital punishment and haven’t drawn any conclusion (read, done any research) about its effectiveness as a deterrent, but I have been firm in believing that the government should not be in the execution business.

I am hardly an activist, but even so I’ve been drawn into vigorous debates about the death penalty with several of my coworkers over the last couple of decades, ranging from a conservative friend right out of college who considered my stance just another part of my liberal pro-Dukakis platform (this was a while ago, and really, I did like Bush Sr.), to one of my project managers several years later who apparently considered my opinion too cerebral and said I should “think with my heart instead of my head”. It seemed to me that heartfelt vengeance wasn’t an improvement over thinking about the issue, but damn my Vulcan logic.

Fortunately, before spending another twenty years repeating and receiving the same arguments, I was rescued by Scott Turow’s https://en.wikipedia.org/wiki/Ultimate_Punishment[Ultimate Punishment: A Lawyer’s Reflections on Dealing with the Death Penalty]. Turow is best known for his legal fiction (it would be crass to lump his work in with the other “legal thrillers”) that frames personal conflict within the complexities and moral ambiguities of the legal system, and his writing resonates with authenticity gleaned from his own practicing legal background. Turow brings the same drama, precision and sincerity to Ultimate Punishment, a factual account of Turow’s experiences with capital punishment, culminating with his service on the Illinois commission that motivated Governor George Ryan to commute the sentences of all death row inmates on his last day in office.

The commission’s initial charter was to propose reforms for an obviously-flawed system that found, though appeal after appeal, one-third of death-row inmates eventually undeserving of the death penalty, or occassionally even wrongly-convicted. Similarly, Turow doesn’t dwell much on the moral and philosophical debates. As a criminal law attorney Turow is familiar with perpetrators of horrible crimes who are unlikely to redeem themselves, and he considers the European view, and alarm, about government-held executions less relevant to the United States.

But that still leaves plenty of more “pragmatic” but no less problematic issues faced by Turow and the comission — for example the death penalty as a deterrent (it’s not), racial criteria in applying the death penalty (it turns out it’s the victim’s race that seems to be the deciding factor), the need for closure by the victims’ families, the risk facing prison staff and inmates from the irredeemably violent, political momentum to apply the death penalty to an ever-widening group of crimes, and inflamed passions of juries and law enforcement in death penalty trials, sometimes extending to outright misconduct by prosecutors and investigators.

Despite the serious and in-depth treatment of this subject, the writing is accessible and the book is not dense, just over 160 pages. Turow’s book is though-provoking and enlightening enough that some references to other readings and resources on capital punishment would be appropriate, e.g. its history in other states and in other parts of the world, but that is more a tribute to this book than a fault. The death penalty is a subject worth constant reevaluation, (even my young ultra-conservative friend had second thoughts after seeing exultant demonstrators at an execution) and Ultimate Punishment should be required reading.
