= What Should I Do With My Life

Like his previous work, https://en.wikipedia.org/wiki/The_Nudist_on_the_Late_Shift[The Nudist on the Late Shift], Po Bronson’s https://www.pobronson.com/index_what_should_I_do_with_my_life.htm[What Should I Do with My Life: The True Story of People Who Answered the Ultimate Question] has an irresistible title. I can’t think of anyone who hasn’t had a moment of doubt about how his or her life has been spent or where it’s going.

In a sense, _What Should I Do with My Life_ doesn’t disappoint. The assorted stories of real people all interesting and some are compelling — I was most moved by the lawyer who became a long-haul truck driver to spend more time with his stepson. I found myself absorbed in the first third of the book, reading about diverse characters such as the apparent slacker who turned out to have a passion for improving golf equipment, and the Hollywood exec who left to do something more worthwhile and ended up back in the movies with renewed appreciation and skill in scriptwriting.

But the book gets more irritating with the increasing mention of Mr. Bronson own experiences. How he turned down a lucrative financial career and turned to writing, how he put together a writer’s commune in San Francisco, how his dependence on his ex-wife held back his writing — these come off as self-absorbed anecdotes. At least he exhibits some embarrassment when describing a side business he ran at his regular workplace without even trying to do a competent job at his paid position.

Even more distracting are the author’s conversations with and judgments of his subjects. Despite his introductory protestations that he doesn’t have the answers, he seems to fancy himself a therapist and career counselor. He’s critical of those who flit among occupations, maintaining that one should stay several years to make a mark. He chastises an accomplished screenwriter for not completely disengaging from Hollywood as originally intended.

No matter how well-intentioned, I find this advice as welcome as the guidance counselors in my high school who told students what careers they were suited for based on a standardized form. The author’s judgments are based on his own experiences (this isn’t my interpretation — he points to his own experiences each time he makes a judgment), but the variety of paths taken in these stories should make clear that one size doesn’t fit all.

Some people are just trying to survive, some are searching for validation, some want a career that defines their lives, and some want jobs that allow them to live one. Mr. Bronson has performed an admirable job in collecting these stories, but I think he’s missed the point — while he expects and urges people to find their calling (which is easy for a successful writer to say), it seems to me the important thing is the journey, not the destination.
