= Winning Arguments

From online reviews, it seems many readers of Stanley Fish’s https://www.harpercollins.com/products/winning-arguments-stanley-fish?variant=32130292711458[Winning Arguments] were disappointed that the book doesn’t actually tell you how to win arguments. It’s actually rather fatalistic in describing futile arguments: those that are full of emotion and recrimination and spiral out of control, and those that are grounded in such opposing viewpoints that rapproachment will never happen.

He does provide some tips, marriage counselor style and actually provided by marriage counselors, on how to get out of arguments by taking a step back and being more objective, by being more empathic, and making concessions. I just find that more discouraging, not just because the author admits they don’t really work for him, either, but because those tactics only work great when the other party reciprocates. Often I’m talking with someone who just wants to win and come out not wrong, and if you give them an opening, they’ll take it. (“Maybe I misunderstood you.” “Yes, you misunderstood me.”)

I do find useful arguments of the sincere information trading variety where you can go in providing your arguments with context saying “This is what I think but on the other hand this and this…” and you can genuinely say “That’s a good point” when someone points out something you overlooked or didn’t know and at the end you can recap with due credit to each person’s observations.

But often I’ve met people who are compulsive, oftentimes defensive, arguers (for some reason, I’ve met a lot from New York). They will argue to win the argument and reflexively hop around spontaneously-generated assertions to keep their momentum going (I blame high school debate for training students to talk really fast just to spew out more points than the opposition).

Sometimes they are recreational arguers who enjoy the process, apparently as a form of conversation, so they’re disappointed if you abstain. But that’s not my idea of fun or time well spent, so my policy toward arguing, if you can’t trust going in unarmed, is similar to Colin Powell’s criteria on invading other countries. Don’t get in unless you think you can win, go in prepared with overwhelming resources, and have an exit strategy.

I do find illuminating the author’s comparison of different arenas of argument, including marital, academic, political (of course) and legal, and the forms argument can take, even visual. And the author, no surprise as an attorney, has a genuine appreciation of argument and considers it a core process of how we develop and operate as a society, though he makes the goal of seeking an objective truth through argument seem like a fool’s errand. I also would have appreciated some tips on how to avoid getting into arguments (or avoiding bad arguments), before it’s too late, but I won’t quibble about that.
