= Writing the Character-Centered Screenplay

There’s something wrong when a book on screenwriting is tedious to get through. Halfway into Andrew Horton’s https://www.ucpress.edu/book/9780520221659/writing-the-character-centered-screenplay-updated-and-expanded-edition[Writing the Character-Centered Screenplay], I thought I would scream if I saw the word carnivalesque again.

By carnival, the author refers to the mystery, progress and interaction of the developing characters in a screenplay. At least, that’s what I think he’s saying in the first chapter, which is devoted to elaboration of this concept. I think this could be stated in a less high-falutin’ manner with “make the characters interesting”. On the other hand, terms like “plasticity”, “potentiality” and “unfinalizedness” send me running back to the carnival.

Some of the author’s points on what makes characters engaging, e.g. unexplained backgrounds and behavior that goes against stereotypes are hard to argue against, and some of his examples are among my favorites, such as Northern Exposure and Lonesome Dove.

But his thesis that character comes first and plot/structure follows at a distant third (I forget what comes second), doesn’t jibe with me. Several of the character-centered movies that he cites, including _Sex, Lies and Videotape_ and _Thelma and Louise_, I thought were undermined by a feeble story and not that compelling character-wise, either. And am I the only one who thought https://en.wikipedia.org/wiki/The_Silence_of_the_Lambs_(film)[Silence of the Lambs] was overrated? Hannibal Lecter was not mesmerizing so much because of his mysterious background, but more so because of the devilish performance by Anthony Hopkins.

And while I’m the first to decry the Bruckheimer-blockbuster formulas, to claim that an emphasis on story and structure is a negative, with Star Wars and Indiana Jones among the culprits, is just too extreme.

Anyway, the latter section of the book does provide some relief in the form of practical advice for screenwriters — the usual tips on coming up with ideas and forming a pitch, listings of software, books, resources for scripts and video libraries, and, surprise, a recipe for gumbo. So at least the author is trying to serve up his own dish of carnival here.
