:toc:

= Lean Agile Scrum Sprints

I miss Waterfall software development. Not the actual process (I always had trouble pretending a stack of design specs wasn’t a work of fiction — in the fantasy genre), but the name. Waterfall is so…tranquil.

Now the trendy methodologies sound like they require daily infusions of Red Bull. First there was Agile, from which sprung Extreme Programming and Scrum, and sprints made their way from Scrum to Design Sprints (to paraphrase Steve Jobs, great designers steal). And this all takes place in Lean Startups.

But who’s kidding who. It’s still a bunch of people wearing headphones and collected around a table staring at screens and tapping away at keyboards, taking breaks to stare at their phones and tap on those keyboards, or, if that’s too much effort, speaking to them. Sweating the day away in a sedentary way.

If there was truth in buzzwording, Agile workplaces would require navigating the office parkour style. “Can you review my code before checkin?” my coworker asks. “Sure,” I say, as I vault over the table between us.

Scrum already has standup meetings, but there should be a real scrum. Or at least some tackling. I can imagine everyone piling on the scrum master as he attempts to reach the corkboard to pin the latest index card. This is a good way to combat feature creep.

Anything with sprints should involve actual running. At standup meetings you could run in place, but laps would be better, perhaps for each person during the five-minute per person go around. That would keep everyone except your resident Ironman from going over the limit.

And I would be disappointed to see a Lean Startup that didn’t only have employees with a BMI under 25. Anyone violating the company policy should do some sprints.
