= FDR Quotes

Long ago, during a meeting with my boss, I quoted someone famous on a technical topic, and my boss countered just because that guy said it doesn’t make it true.

Now, I was just trying to provide proper attribution and never really got along with my boss, but he did have a point. More generally, even if something is true, just because someone famous said it doesn’t necessarily impart more weight to it. It might even detract from the point of the quote.

For example, I frequently see quotes from the eminently quotable Franklin Delano Roosevelt, and they are fine quotes about freedom and such that no one should disagree with. However, he is the President who signed the executive order interning over a hundred thousand Japanese-Americans, entire families, women, children, most of them native-born US citizens, in barbed wire desert camps for the duration of World War II (with some released in order to serve in combat).

Although it seems to be agreed upon by most (but somehow not all), that the internment was a travesty of justice (even back then, there were many who knew it was wrong), FDR seems to get a pass on it. So next time you see a quote from him, try appending (as I do mentally) what I just said above, or the short version:

[quote,FDR]
____
…said the guy who ordered the internment of Japanese-Americans.
____

Here, you can practice on this selection I just grabbed from goodreads:

____
The only thing we have to fear is fear itself.
____

____
Remember, remember always, that all of us, and you and I especially, are descended from immigrants and revolutionists.
____

____
If you treat people right they will treat you right … ninety percent of the time.
____

____
Human kindness has never weakened the stamina or softened the fiber of a free people. A nation does not have to be cruel to be tough.
____

____
Better the occasional faults of a government that lives in a spirit of charity than the consistent omissions of a government frozen in the ice of its own indifference.
____

____
True individual freedom cannot exist without economic security and independence. People who are hungry and out of a job are the stuff of which dictatorships are made.
____

____
Great power involves great responsibility.
____

____
In the truest sense, freedom cannot be bestowed; it must be achieved.
____

____
Today we are faced with the pre-eminent fact that if civilization is to survive, we must cultivate the science of human relationships, the ability of all peoples of all kins to live together and to work together in the same world at peace.
____

____
It is the purpose of government to see that not only the legitimate interests of the few are protected but that the welfare and rights of the many are conserved.

____
There should be no bitterness or hate where the sole thought is the welfare of the United States of America. No man can occupy the office of President without realizing that he is President of all the people.
____
