= The Design of Everyday Things, In Today’s Mailbag

If any book has given me an epiphany, it’s Donald Norman’s The Design of Everyday Things. Just his example of that blinking VCR clock that’s always blinking because no one could figure out how to set the time (if you’re too young to know what I’m talking about, well, microwaves still have that issue), imprinted on me the realization that almost every interface, if not every, could be improved, and it’s not that hard to think of improvements, if you just think about it.

You can make it an exercise to just look around and notice what could be improved and how. Today I found some easy examples, just in my mail (the postal kind).

First, I had a bill from my opthamalogist. It’s not a work of art (my own invoices are formatted better), but the portion that I’m supposed to tear off and send in with payment actually has the address to send it to. That might not seem like such a big deal, but most of my doctors’ bills didn’t bother to do that, so I’d tear off the form, attach payment and start to address the envelope only to realize I had to find out where I put the rest of the form because that’s where the address is printed.

And I’ve seen worse – even cases where they didn’t bother to put the amount you owe on the payment form, so I’ve been caught delivering a payment in person only to find I didn’t know how much to make the check out for.

The other example today is the result of a confluence where I received two new ATM cards (perhaps indicating I have too many bank accounts). The activation process was similar for both: call a number and enter the card number. However, one of them required you to hit # when done and the other didn’t. Again, not a huge deal, but think about it – you can only enter a fixed number of digits and there’s no backspace, so there’s no reason to require you to hit # at the end, the underlying code just needs to check if you’ve entered 16 digits.

Actually, the lack of backspace/delete is a fundamentally inconvenient aspect of this process (I managed to enter a number incorrectly three times and had to wait for some timeout period to expire and let me start entering the number from the beginning), so it would be nice to have a cancel/restart button. Like #.

That’s it for the design of today’s things.
