= Writing the User Interface

When people talk about user interface design these days (or UX as the cool kids call it), it’s usually about layout, colors, fonts, widgets, gestures…but if there’s text, the actual words are just as important as anything else.

As an example, I’m going to pick on Unity because I noticed a couple of things just recently. This email promoting their extended services has a “Submit your request” button and links to web pages that also have “Submit your request” buttons.

What’s my request? Request the product? Request a quote? Request info? Request a phone call? Assuming it’s request info, then “Request Info” would be a better button label.

And someone pointed out on the Unity forum that the Unity Connect privacy settings phrasing is a head-spinner. Aside from the awkward phrasing, the subhead Data Processing conveys no useful information and turning a switch on to enable opt-out is confusing, like agreeing to a double negative.

So I recommended some refactoring: the subhead should be “Allow Connect to use your data to recommend” and each of the options would be phrased like “People you might want to follow” and the switch on means Yes, allow it.

This is an example why you might want to include good writers on your staff. Or hire designers who are good writers.
