:toc:

= Blade Runners

I don’t see a lot of movies in the theater, but I did see the new Blade Runner, and it was beautiful and moving. However, I still had my standard complaint about how sci-fi movies of the future, especially those that make a point of showing off a lot of artifacts of Asian culture, show fewer Asians than you would find in a Southern California mall or occupying cubicles in a Bay Area tech company.

And they’re never Asian American. It was a total turnoff for me in Ready, Player, One when the sole two Asians with speaking parts (I did spy a young Asian woman extra in a crowd), appeared to have just recently arrived from Asia. That’s likely a faithfulness to the book, which I didn’t finish, but the book made me appreciate Snow Crash (and the movie made me appreciate the Final Fantasy), which I just finished reading for the third time. I hope the talk of a long-overdue Snow Crash movie takes place, because if they’re faithful to that book, the lead will be an African-Asian-American. Also, I can see Jason Momoa as Raven. I’m just throwing that out there.

Anyway, on a recent flight they had both Blade Runner movies (Jet Blue Mint!), and though I started watching the new one first, I switched to the original, so I guess the first one, even with the Harrison Ford narration, is more special to me. Here’s a bit I wrote about several years ago (apparently before I got a Blue-Ray player):

In one of the many interesting featurettes in recently released Blade Runner: The Final Cut DVD set, a staff member of BladeZone asserts there are only people who hate Blade Runner and people who love Blade Runner. Well, not me. I do have some special memories of Blade Runner — it was my first R-rated movie (a high school hacker friend and his father invited me along) and probably the first time I saw on-screen boobs. I did like the movie a lot more than the critics who panned it — I felt they just didn’t get sci-fi at all. And I remember attending a meeting for volunteers at the MIT Media Lab during the winter break period (Intersession Activities Period, I think), in which one of the Lab students invited us to help him create a “loose-sync” multimedia project that, as far as I could tell, just randomly zipped among Blade Runner scenes. I thought it was a silly project, but it gave me an inkling of the film’s influence, despite it’s lack of initial commercial success.

But Blade Runner didn’t make as much an impression on me as Star Wars (or, for that matter, Ridley Scott’s previous film, Alien, which really freaked me out), and it’s not my favorite sci-fi work (2001, Firefly, the new Battlestar Galactica) On the other hand, it does have staying power. I still have the 1991 laserdisc director’s cut (and I definitely prefer it without the voiceover), it was the film that got me to eventually read Philip K Dick, and I’ve spent a couple of weeks watching all five DVD’s in this new set.

The highly interesting featurettes documenting the film’s influence and the battles between Ridley Scott and the studio, between the director and the crew (they got the impression the English director didn’t like working with Hollywood crew, and it seems they were at least partly right), the writing struggles, disagreements over casting, budget and schedule issues, and even some disgruntlement by Harrison Ford gave me a greater appreciation of the film and its creation. If you want to see everything, make sure you don’t just hit Play All on each of the DVD’s — there are some segments that are played separately, and thus easily overlooked.

When Blade Runner hit the theaters, I didn’t take seriously a concern that the portrayal of a future LA filled with Asians could stoke anti-Asian sentiment — this was back in the days when Buy American meant don’t buy Japanese, and the skyscrapers of Blade Runner LA are covered with video billboards of geishas proferring wares.

But now that I live in LA (I first saw the movie when I lived in Iowa), I look at ethnic composition in the film and think, waah? The skies are filled with video billboards featuring geishas, but as far as I can tell, all the Asian characters on the street are Chinese (certainly the case with theTsingtao beer Harrison Ford orders). That reminds me of an IT colleague who wanted to try out the Japanese restaurant in his neighborhood — turned out to be a Chinese seafood restaurant, yet once there he still said he wanted “gyoza, gyoza, gyoza!” And the Chinese peasants peddling bicycles and wearing coolie hats — where did that come from? I’m just glad there weren’t rickshaws (although a futuristic one designed by Syd Mead might have been cool)

It makes more sense after viewing the featurette on the film’s art direction. Despite the emphasis on Asian influences, the entire art department seems to have been white and just went with what looked cool, like the people now who sport Chinese character tattoos that don’t mean what they think.

But Asians fare better than other minorities — Edward James Olmos presents one of the most interesting characters in the film despite less screen time, but it does bother me a bit that the one identifiable Latino sort of looks like a pimp. An LA with white rich people and white seedy cops straight out of film noir, Japanese commercialism, elderly Chinese who look like they’ve spent their lives in Chinatown or a rice paddy, one Latino pimp, and no African-Americans. Well, maybe that was the British view of LA.
