= Stay Home If You’re Asian

It’s hard to self-isolate, but one thing that helps keep me inside is being an Asian American. Not unpredictably after Trump’s Chinese-branding of the coronavirus (for once, he didn’t name something after himself, but personally I think “Trump virus” or “MAGA plague” sound about right), coronavirus-inspired hate crimes against Asian Americans are happening.

I checked the latest Las Vegas-area virus case stats from the Southern Nevada Health District, and at five percent Asians are well below their demographic (ten percent, according to the census).
Image for post
Image for post

Although I suppose there could be a lot of Asians in Unknown (and who could blame them for not telling?)

It’s easy to blame Trump, but that’s too easy. As with the treatment of refugees at our southern border, politicians of “both sides” have been complicit in letting this happen. This election season has been the first time I’ve seen Democrats grow a backbone on immigration. When I lived in California, I couldn’t find any mention of immigration in the issues list on Dianne Feinstein’s web site. Even this campaign season, the Democratic candidates still prefaced every mention of immigration with “Yes we need border security” (Andrew Yang’s site mentioned it twice: “Border security…DACA…Border security…”)

And I winced when Bernie Sanders first ran for president and while debating Hillary Clinton addressed a mostly white New England audience with “You shouldn’t have to compete against Mexicans and Asians who are making…” (I more than winced, I stopped watching the debate and started supporting Hillary). When I brought that up in response to his twitter account encouraging everyone to “if you see something, say something” about racism, a bunch of Bernie-can-do-no-wrongers whitesplained to me what he “really” meant. I. Don’t. Care. It’s the type of careless or not-so-careless framing that can get people killed, like when Vincent Chin was beaten to death by unemployed auto workers in Detroit who thought he was Japanese (or didn’t care about the difference) while politicians like Dick Gephardt conducted Asia-blaming campaigns. By the way, Chin’s murderers served no time.

Before the Sanders zealots complain that I’m just picking on him, I also reminded Kamala Harris’s twitter account, when she brought up Earl Warren as an inspiration (contrasting with Brett Kavenaugh, whose Supreme Court confirmation was in progress) that Warren was instrumental in the World War II internment of 120,000 Japanese Americans (the executive order was signed by FDR, another hero of progressives). So you could say he really exceeded expectations as a Supreme Court justice.

As far as I know, the subject is still not mentioned much in school history classes (although when I lived in Huntington Beach, the city distributed a self-produced centennial history video to schools which bizarrely defended the internment). It has come up more often during the Trump administration, particularly with the Muslim bans. At the time, I tweeted that Chinese-Americans who didn’t care about the Muslim ban or the treatment of refugees at the border should remember the internment and consider, we could be next. And here we are.
