= Leaving MIT

An online account that provides no option to delete the account inevitably makes me want to delete the account. So I had to email the MIT alumni association to delete my account. That was just one of the small reasons for removing it. Another was receiving class emails even after unsubscribing a year earlier (apparently alumni spam works just like regular marketing spam).

But the big impetus is the MIT Epstein scandal. The whole thing stinks: the hobnobbing (and worse, if the Minsky allegation is true), the money, the coverup…and the total lack of reflection on the constant drive for donations, no less money-grubbing than corporate profit-seeking but cloaked in the idealism of higher education.

As a student, I didn’t like seeing freshmen recruited into fundraising callathons (and as a part-time employee, I saw the Institute was not particularly well-run as an organizaation), as a graduate I was annoyed that the first call I received from a classmate was a solicitation for a class donation, and as a recent class officer I was astonished there’s an annual alumni conference focused on fundraising. It looked to me like the entire alumni association is a machine for generating donations, and I felt a bit used.

Sure, it’s nice to connect with old (and getting old) classmates, but frankly, I didn’t get around that much while in school, so there aren’t that many to keep in touch with, anyway. And it’s nice to have that lifetime Technology Review subscription. When I applied to MIT, someone told me Technology Review was the best science and tech magazine, and for a long time I agreed.

Lately, however, either my standards have changed or they’ve gone downhill. It’s seemed to me too yay science and rah rah Institute, with some writing that bordered on the unprofessional (one writer complained about “mouth breathers” — hey, anti-nerd, much?), which I also feel was exhibited when they edited the class notes I submitted as an officer (they removed quote marks from a press release I quoted, which by the way they submitted to me for inclusion, so once againI felt I was working for them for free). And don’t get me started on their annual 35-under-35 issue (hey, let’s copy Forbes, the shallow part!)

More importantly, Tech Review really missed the boat on Epstein. I don’t expect them to make a big NYT-like scoop on that sort of thing, but in all those years, decades even, as a journalistic endeavor with instituational access, there should have been some examination of the Institute’s questionable practices (maybe the student paper does a better job). So I’m fine with canceling my account and terminating my lifetime subscription. Besides, there’s always the web site.

I always thought MIT was superior to other schools in some cultural and ethical ways (e.g. no legacy and celebrity admissions or sports scholarships, although who knows, admissions is still a subjective and opaque process, and there was that Ivy Group financial aid collusion lawsuit). I still like to think MIT is better, but now I realize it’s not much better.
